### ISSUE TITLE
Thanos compactor failing to start with first pass of downsampling failed error

### ISSUE THREAD

**Issue by infa-mlagad** [thanos-io/thanos#5272] opened 2022-04-08 06:47 UTC
**Thanos, Prometheus and Golang version used**:
Thanos image version - v.0.25.1

**Object Storage Provider**:
AWS

**What happened**:
Thanos compactor going in crashlooping state. Below error in the logs.
`level=warn ts=2022-04-08T06:41:18.018546402Z caller=intrumentation.go:67 msg="changing probe status" status=not-ready reason="error executing compaction: first pass of downsampling failed: downsampling to 60 min: downsample block xxxx to window 3600000: expected downsampled chunk (*downsample.AggrChunk) got *chunkenc.XORChunk instead for series: 6566"
level=info ts=2022-04-08T06:41:18.018588894Z caller=http.go:84 service=http/server component=compact msg="internal server is shutting down" err="error executing compaction: first pass of downsampling failed: downsampling to 60 min: downsample block xxxx to window 3600000: expected downsampled chunk (*downsample.AggrChunk) got *chunkenc.XORChunk instead for series: 6566"
level=info ts=2022-04-08T06:41:18.019725719Z caller=http.go:103 service=http/server component=compact msg="internal server is shutdown gracefully" err="error executing compaction: first pass of downsampling failed: downsampling to 60 min: downsample block xxxx to window 3600000: expected downsampled chunk (*downsample.AggrChunk) got *chunkenc.XORChunk instead for series: 6566"
level=info ts=2022-04-08T06:41:18.019767702Z caller=intrumentation.go:81 msg="changing probe status" status=not-healthy reason="error executing compaction: first pass of downsampling failed: downsampling to 60 min: downsample block xxxx to window 3600000: expected downsampled chunk (*downsample.AggrChunk) got *chunkenc.XORChunk instead for series: 6566"
level=error ts=2022-04-08T06:41:18.019863334Z caller=main.go:158 err="downsampling to 60 min: downsample block xxxx to window 3600000: expected downsampled chunk (*downsample.AggrChunk) got *chunkenc.XORChunk instead for series: 6566\nfirst pass of downsampling failed\nmain.runCompact.func7\n\t/app/cmd/thanos/compact.go:449\nmain.runCompact.func8.1\n\t/app/cmd/thanos/compact.go:485\ngithub.com/thanos-io/thanos/pkg/runutil.Repeat\n\t/app/pkg/runutil/runutil.go:75\nmain.runCompact.func8\n\t/app/cmd/thanos/compact.go:484\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nerror executing compaction\nmain.runCompact.func8.1\n\t/app/cmd/thanos/compact.go:512\ngithub.com/thanos-io/thanos/pkg/runutil.Repeat\n\t/app/pkg/runutil/runutil.go:75\nmain.runCompact.func8\n\t/app/cmd/thanos/compact.go:484\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\ncompact command failed\nmain.main\n\t/app/cmd/thanos/main.go:158\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"`
**What you expected to happen**:
Thanos compactor should run without error. 
**How to reproduce it (as minimally and precisely as possible)**:
Deploy thanos components of v0.25.1 in AWS EKS , with S3 for object storage. 

Kindly help!!

**Comment by infa-kparida** [comment] 2022-04-18 06:20
Could someone look into this.We are not able to make the compactor run.Even we see few other people are getting similar error https://cloud-native.slack.com/archives/CK5RSSC10/p1649679069949859.

This is happening when there are large amount of data compactor is trying to downsample.

**Comment by genie88** [comment] 2022-04-20 12:22
we also encounter same problem :)

**Comment by infa-kparida** [comment] 2022-04-27 04:25
Can someone look into this issue.We are struggling since almost 4 weeks to fix this and still dont have any solution

**Comment by infa-kparida** [comment] 2022-05-18 02:33
Anyone able to solve this ?

**Comment by eharcevs** [comment] 2022-06-30 07:55
I investigated the issue and I think I found the reason:

As @nikitapecasa noted above the error occurs when compactor tries to downsample a block of 5m resolution to 1h resolution. It expects all chunks to be of type `AggrChunk`, but encounters an "empty" `XORChunk` and returns the error.
The question is - how did this `XORChunk` end up in a downsampled block?

I think it appeared during vertical compaction of downsampled blocks. During compaction chunks are being merged using the `storage.NewCompactingChunkSeriesMerger(storage.ChainedSeriesMerge)` function.
If the cunks overlap the function tries to "merge" them, but apparently it only knows how to handle `XORChunk`s and not `AggrChunk`s. It calls `NewSeriesToChunkEncoder` which explicitly createts `XORChunk`s and returns them in result, and that's how a `XORChunk` appears where only `AggrChunk`s are expected.
Here is a test case to reproduce the issue:
https://gist.github.com/eharcevs/5938b493fcf319e2b302a73ccfceb178

I think there are 2 parts to the solution:
1. Make sure the compactor doesn't crash during downsampling if it encounters a `XORChunk` when only `AggrChunks` are expected. 
   If it happens, the chunk is already corrupted and there is nothing we can do about it at this point. Maybe we should just skip this chunk (logging a warning) and continue?
   Or skip downsampling of the entire block? Whatever we do, the compactor shouldn't crash IMHO.
2. Fix merging of overlapping `AggrChunk`s.

wdyt?

**Comment by bwplotka** [comment] 2022-07-01 10:01
Thanks for this investigations! Why not checking if chunk is empty and skipping it safely? (: Will comment on PR! Thanks.

**Comment by eharcevs** [comment] 2022-07-01 11:38
Thanks for the feedback @bwplotka , adjusted the PR! That should make the downsampling process more resilient. 
What are your thoughts about fixing the root cause of this issue - merging of overlapping `AggrChunk`s during compaction?
Should I open a separate issue for this?
I would like to try fixing it, but not sure about the right approach. One idea: since `AggrChunk` is a "wrapper" which contains 5 `XORChunk`s, what if we "unwrap" those, merge corresponding `XORChunk`s, and "wrap it up" again? Does it make sense mathematically?
Sorry for so many questions :) any feedback is much appreciated

**Closed** 2022-07-07 02:25 UTC
Labels: bug, component: compact, needs-investigation
