### ISSUE TITLE
How to delete s3 object metrics from thanos component

### ISSUE THREAD

**Issue by satyabhama** [thanos-io/thanos#1957] opened 2020-01-08 06:53 UTC
We are using thanos with prometheus.
We are storing metrics into s3 storage object.
Now we are trying to delete data for particular prometheus job , How we should do this??
Which thanos component we should use?? ex. sidecar,query...etc

**Comment by squat** [comment] 2020-01-08 09:03
Thanos does not have its own workflow or component for deleting metrics today. Note that time series are all stored together in Prometheus TSDB blocks, so if you want to remove a time series today you have to delete the entire block holding it, which would also eliminate all co-located time series

This is a pending feature for Thanos. Help wanted.

Closing as a duplicate of https://github.com/thanos-io/thanos/issues/1598

**Closed by squat** 2020-01-08 09:03 UTC
