### ISSUE TITLE
query: rate sometimes become wrong when counter reset & dedup enabled

### ISSUE THREAD

**Issue by Wing924** [thanos-io/thanos#1788] opened 2019-11-26 07:12 UTC
**Thanos, Prometheus and Golang version used**:
thanos v0.8.1
prometheus v2.13.1

**Object Storage Provider**:
S3

**What happened**:
* I monitoring logstash with metrics `logstash_event_in_total`, which is a counter for count of  incoming events.
* I restart logstash => this metrics resets and start from 0
* logstash_event_in_total{hostname=~"xxxxx"}[10m]
* `rate(logstash_event_in_total[2m])` without dedup => OK
* `rate(logstash_event_in_total[2m])` with dedup => NG

with dedup
<img width="1361" alt="スクリーンショット 2019-11-26 15 41 22" src="https://user-images.githubusercontent.com/8895721/69605409-60334180-1063-11ea-8e1c-d1759c3f4281.png">

without dedup
<img width="1368" alt="スクリーンショット 2019-11-26 15 42 11" src="https://user-images.githubusercontent.com/8895721/69605441-72ad7b00-1063-11ea-9aad-6501aa5a2eed.png">

**What you expected to happen**:
both w/ and w/o dedup return al most same graph

**raw data**:

| relative time | replica-1 series | replica-2 series |
| ------------- | ---------------- | ---------------- |
| 0             | 668153           |                  |
| 7             |                  | 668156           |
| 15            | 668173           |                  |
| 22            |                  | 668179           |
| 30            | 668189           |                  |
| 37            |                  | 668202           |
| 45            | 668221           |                  |
| 52            |                  | 668226           |
| 60            | 668234           |                  |
| 67            |                  | 668248           |
| 75            | 668262           |                  |
| 82            |                  | 668271           |
| 135           | 0                |                  |
| 142           |                  | 0                |
| 150           | 0                |                  |
| 157           |                  | 18               |
| 165           | 31               |                  |
| 172           |                  | 35               |
| 180           | 43               |                  |
| 187           |                  | 60               |
| 195           | 73               |                  |

**Comment by bwplotka** [comment] 2019-11-28 12:41
Thanks for report! Let's create unit test for it and see where the problem lies in our deduplication logic.

Something that we would need as well is raw data for raw metrics in this case, not rated, so `logstash_event_in_total{hostname=~"mon-srelog-gateway106z"}`

**Comment by Wing924** [comment] 2019-11-28 13:32
@bwplotka this is raw samples
<img width="1325" alt="スクリーンショット 2019-11-28 22 24 31" src="https://user-images.githubusercontent.com/8895721/69810220-bf917d00-122e-11ea-9df1-415819d1b0dd.png">

replica-1:
```
668202 @1574746567.292
668226 @1574746582.292
668248 @1574746597.292
668271 @1574746612.292
0 @1574746672.292
18 @1574746687.292
35 @1574746702.292
60 @1574746717.292
82 @1574746732.292
112 @1574746747.292
129 @1574746762.292
167 @1574746777.292
188 @1574746792.292
222 @1574746807.292
237 @1574746822.292
258 @1574746837.292
273 @1574746852.292
```
replica-2:
```
668221 @1574746575.753
668234 @1574746590.753
668262 @1574746605.753
0 @1574746665.753
0 @1574746680.753
31 @1574746695.753
43 @1574746710.753
73 @1574746725.753
98 @1574746740.753
121 @1574746755.753
150 @1574746770.753
175 @1574746785.753
207 @1574746800.753
231 @1574746815.753
243 @1574746830.753
271 @1574746845.753
282 @1574746860.753
```

**Comment by Wing924** [comment] 2020-01-14 12:23
@bwplotka any update on this?

**Comment by FUSAKLA** [comment] 2020-01-19 22:09
Not sure but might be dupe of https://github.com/thanos-io/thanos/issues/1326 ?

Seems very similar, I have the unit test somewhere and still have it on my TODO list to have a closer look.

**Comment by Wing924** [comment] 2020-02-18 23:49
any updates？

**Comment by bwplotka** [comment] 2020-02-19 08:46
Nope, still to be done. Help wanted! (:

**Comment by bwplotka** [comment] 2020-03-20 10:18
Still valid.

**Comment by bwplotka** [comment] 2020-04-20 12:21
valid - to investigate still

**Comment by bwplotka** [comment] 2020-05-12 11:28
duplicate of https://github.com/thanos-io/thanos/issues/2401 and we found root cause! (: Fix should be today.

**Closed by bwplotka** 2020-05-12 11:28 UTC
