### ISSUE TITLE
thanos-sidecar : link: can't create hardlink : Operation not supported

### ISSUE THREAD

**Issue by desourav** [thanos-io/thanos#2210] opened 2020-03-02 22:05 UTC
**Thanos, Prometheus and Golang version used**:
Prometheus : 2.12.0
Thanos : 0.7.0

**Object Storage Provider**:
s3 COS

**What happened**:
I'm using cloud object store bucket as Persistent Volume for Prometheus TSDB.
Thanos sidecar unable to ship the metrics.

**What you expected to happen**:
Thanos sidecar to ship the metrics.

**How to reproduce it (as minimally and precisely as possible)**:
Create the prometheus thanos setup with the persistent volume on /var/prometheus

**Full logs to relevant components**:

```
level=info ts=2020-03-02T05:57:29.051413338Z caller=shipper.go:349 msg="upload new block" id=01E2BYC26N101VPVQHG1718SP9
level=debug ts=2020-03-02T05:57:29.104221452Z caller=prometheus.go:190 component=sidecar msg="started handling ReadRequest_SAMPLED response type."
level=debug ts=2020-03-02T05:57:29.104382183Z caller=prometheus.go:233 component=sidecar msg="handled ReadRequest_SAMPLED request." series=2
level=debug ts=2020-03-02T05:57:29.104524142Z caller=prometheus.go:190 component=sidecar msg="started handling ReadRequest_SAMPLED response type."
level=debug ts=2020-03-02T05:57:29.104564151Z caller=prometheus.go:233 component=sidecar msg="handled ReadRequest_SAMPLED request." series=0
level=debug ts=2020-03-02T05:57:29.120475292Z caller=prometheus.go:190 component=sidecar msg="started handling ReadRequest_SAMPLED response type."
level=debug ts=2020-03-02T05:57:29.121000689Z caller=prometheus.go:233 component=sidecar msg="handled ReadRequest_SAMPLED request." series=2
level=debug ts=2020-03-02T05:57:29.131337472Z caller=prometheus.go:190 component=sidecar msg="started handling ReadRequest_SAMPLED response type."
level=debug ts=2020-03-02T05:57:29.13145341Z caller=prometheus.go:233 component=sidecar msg="handled ReadRequest_SAMPLED request." series=0
level=debug ts=2020-03-02T05:57:29.455611385Z caller=prometheus.go:190 component=sidecar msg="started handling ReadRequest_SAMPLED response type."
level=debug ts=2020-03-02T05:57:29.455791565Z caller=prometheus.go:233 component=sidecar msg="handled ReadRequest_SAMPLED request." series=2
level=error ts=2020-03-02T05:57:29.559256813Z caller=shipper.go:316 msg="shipping failed" block=01E2BYC26N101VPVQHG1718SP9 err="hard link block: hard link file chunks/000001: link /var/prometheus/01E2BYC26N101VPVQHG1718SP9/chunks/000001 /var/prometheus/thanos/upload/01E2BYC26N101VPVQHG1718SP9/chunks/000001: operation not supported"
level=info ts=2020-03-02T05:57:29.570306182Z caller=shipper.go:349 msg="upload new block" id=01E2C57SEN0ZEAEDXQDQCS0BGH
level=debug ts=2020-03-02T05:57:29.638062816Z caller=prometheus.go:190 component=sidecar msg="started handling ReadRequest_SAMPLED response type."
level=debug ts=2020-03-02T05:57:29.638217115Z caller=prometheus.go:233 component=sidecar msg="handled ReadRequest_SAMPLED request." series=2
level=error ts=2020-03-02T05:57:30.00886676Z caller=shipper.go:316 msg="shipping failed" block=01E2C57SEN0ZEAEDXQDQCS0BGH err="hard link block: hard link file chunks/000001: link /var/prometheus/01E2C57SEN0ZEAEDXQDQCS0BGH/chunks/000001 /var/prometheus/thanos/upload/01E2C57SEN0ZEAEDXQDQCS0BGH/chunks/000001: operation not supported"
level=info ts=2020-03-02T05:57:30.020529304Z caller=shipper.go:349 msg="upload new block" id=01E2CC3GPTJZS7X0R27J5T7M89
level=debug ts=2020-03-02T05:57:30.06151356Z caller=prometheus.go:190 component=sidecar msg="started handling ReadRequest_SAMPLED response type."
level=debug ts=2020-03-02T05:57:30.061668397Z caller=prometheus.go:233 component=sidecar msg="handled ReadRequest_SAMPLED request." series=2
level=debug ts=2020-03-02T05:57:30.117953878Z caller=prometheus.go:190 component=sidecar msg="started handling ReadRequest_SAMPLED response type."
level=debug ts=2020-03-02T05:57:30.118090003Z caller=prometheus.go:233 component=sidecar msg="handled ReadRequest_SAMPLED request." series=1
level=error ts=2020-03-02T05:57:30.451821531Z caller=shipper.go:316 msg="shipping failed" block=01E2CC3GPTJZS7X0R27J5T7M89 err="hard link block: hard link file chunks/000001: link /var/prometheus/01E2CC3GPTJZS7X0R27J5T7M89/chunks/000001 /var/prometheus/thanos/upload/01E2CC3GPTJZS7X0R27J5T7M89/chunks/000001: operation not supported"
```

**Comment by desourav** [comment] 2020-03-02 23:06
It seems Cloud Object Storage doesnt support hard link. Is there a workaround to this?

**Comment by daixiang0** [comment] 2020-03-03 02:06
Maybe you can google with COS or ask COS community, it is not thanos issue indeed.

**Comment by desourav** [comment] 2020-03-03 02:31
@daixiang0 the COS community states that the object store is well, an object store, and cannot create hard links. As a workaround can I do this?

As the shipper is unable to create a hardlink, can I just copy the chunks to the destination instead? I noticed if I copy them, they disappear (not sure if they are consumed or shipper rejects them).
 
```
for i in `ls -lrt /var/prometheus | grep "drw" | grep -v "wal" | grep -v "thanos" | awk '{printf $9 "\n"}'`; do mkdir -p /var/prometheus/thanos/upload/$i/chunks && cp /var/prometheus/$i/chunks/* /var/prom
etheus/thanos/upload/$i/chunks/; done

```

**Comment by jojohappy** [comment] 2020-03-03 05:08
> As the shipper is unable to create a hardlink, can I just copy the chunks to the destination instead? I noticed if I copy them, they disappear (not sure if they are consumed or shipper rejects them).
@desourav No, thanos will clean and re-create the hard link when uploading new blocks.

Make sure you're not out of disk space, and you have full permissions to your prometheus data directory.

**Comment by huongbn** [comment] 2020-03-03 05:39
I have same problem with you, I'm testing with Ceph S3 but noy success

**Comment by desourav** [comment] 2020-03-03 14:18
> > As the shipper is unable to create a hardlink, can I just copy the chunks to the destination instead? I noticed if I copy them, they disappear (not sure if they are consumed or shipper rejects them).
> 
> @desourav No, thanos will clean and re-create the hard link when uploading every new blocks.
> 
> Make sure you're not out of disk space, and you have full permissions to your prometheus data directory.

@jojohappy I have the prometheus tsdb (/var/prometheus dir) in Cloud Object Store, hence the out of disk space is not a concern. In fact I moved it to COS for the same reason (the tsdb never gets device out of space).

@jojohappy @daixiang0 can you change the shipper code to default to the current logic, but have a different approach if say, `--tsdb-object-store=true`, because : 

1. keeping prometheus tsdb in COS makes sense as its a reliable data storage
2. the prometheus pod doesn't evict anymore 
3. crucial to COS, it cannot support hard links, hence making it copy the files to the destination `thanos/uploads` dir could be an alternative.

**Comment by GiedriusS** [comment] 2020-03-07 17:14
The problem is that the file-system you are using doesn't support hard-links and/or you are trying to make hard-links across file-system boundaries. We absolutely need them and cannot change the logic because the Prometheus might delete the block we are trying to upload during the next pass of its compaction loop. I hope that makes sense. Closing this issue as it is not Thanos related and, unfortunately, we cannot support such setups ATM due to pretty valid reasons, IMO.

**Closed by GiedriusS** 2020-03-07 17:14 UTC
Labels: need-more-info, question

**Comment by daixiang0** [comment] 2020-03-09 01:39
This change is easy but need to think more.

cc @bwplotka

**Comment by jsfrerot** [comment] 2023-03-01 18:32
Here is the workaround I used. Prometheus and Thanos are not running as docker containers in my setup. We set it up with puppet. So we simply set thanos and prometheus run as the same user (prometheus). Then the hardlink issue doesn't cause any issues anyomre.
Puppet's thanos module starts thanos with the "thanos" user with is different from the "prometheus" user used with prometheus.
