### ISSUE TITLE
[Thanos Store] Redis cache not working

### ISSUE THREAD

**Issue by grootsadmin** [thanos-io/thanos#6498] opened 2023-07-04 12:23 UTC
Configured thanos store with s3 bucket and redis caching but got the following error, this operation takes huge CPU utilization and disk iowait is high 100MB/S

SET CACHE:
level=warn name=store ts=2023-07-04T12:18:32.181714344Z caller=redis_client.go:259 msg="failed to set item into redis" err="context canceled" key=S:01H3E
QMB4575THRK85EN5ZXJAV:5396976 value_size=74

GET CACHE:
level=warn name=store ts=2023-07-04T12:18:33.350243132Z caller=redis_client.go:303 msg="failed to mget items from redis" err="context deadline exceeded" items=0

**Environment**:
- thanos, version 0.31.0 (branch: HEAD, revision: 50c464132c265eef64254a9fd063b1e2419e09b7)
  build user:       root@63f5f37ee4e8
  build date:       20230323-10:13:38
  go version:       go1.19.7
  platform:         linux/amd64

- PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
- Kernel : Linux Thanos-Store 5.19.0-1024-aws #25~22.04.1-Ubuntu SMP Tue Apr 18 23:41:58 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by GiedriusS** [comment] 2023-07-11 08:53
(1) is fixed by https://github.com/thanos-io/thanos/pull/6180, (2) is a good first issue. We should simply return immediately if no keys were requested.

**Comment by heysujal** [comment] 2023-07-12 12:05
@GiedriusS I am new to this project and would like to work on this issue.
Please tell me things that I should know to work on this.

**Comment by GiedriusS** [comment] 2023-07-12 12:19
Actually, my bad: https://github.com/thanos-io/thanos/blob/50c464132c265eef64254a9fd063b1e2419e09b7/pkg/cacheutil/redis_client.go#L303. That `items=0` just means that we haven't been able to receive any items. I don't think there's anything to do here. These errors just mean that retrieving data has timed out. I'd suggest @grootsadmin check whether the compactor is running well in your setup. That's the most likely cause of the huge Thanos Store load. We actually test Redis in tests so it must be something on your end. Closing the issue, please comment if anything comes up or if there are some instructions how we could reproduce it.

**Closed by GiedriusS** 2023-07-12 12:19 UTC
Labels: difficulty: easy, good first issue, component: store

**Comment by grootsadmin** [comment] 2023-07-13 09:26
When query to historical data then got the error
store[434966]: level=warn name=store ts=2023-07-13T09:25:43.470276936Z caller=redis_client.go:259 msg="failed to set item into redis" err="context deadline exceeded" key=P:01H3ERFSZEHCPYY5G3Z1EJ71JF:IwzhNtZFoIDcE0Qgi-HoImSRcrEi0tTB_7Lb9DUT2Z8 value_size=3223

**Comment by grootsadmin** [comment] 2023-07-13 09:28
Not able to SET and GET
store[434966]: level=warn name=store ts=2023-07-13T09:27:18.43347688Z caller=redis_client.go:259 msg="failed to set item into redis" err="context canceled" key=S:01H4DG3MH6ZSQR3RJN94D86521:5491184 value_size=74

You can reproduce using add redis as cache index and query historical data and verify

**Comment by GiedriusS** [comment] 2023-07-13 09:29
`context canceled` has been fixed in https://github.com/thanos-io/thanos/pull/6180. `context deadline exceeded` means that Redis hasn't responded in the given timeout. You can either try raising the timeout or adding more replicas to your Redis cluster.

**Comment by grootsadmin** [comment] 2023-07-13 09:33
ill check and confirm, Thanks

**Comment by grootsadmin** [comment] 2023-07-13 10:35
I tried to use AWS redis elasticache but got the error
Jul 13 15:59:40 Thanos-Store-Receiver-0 systemd[1]: thanos-store.service: Consumed 15.635s CPU time.
Jul 13 15:59:40 Thanos-Store-Receiver-0 systemd[1]: Started CloudNetra Thanos Storage.
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: level=info name=store ts=2023-07-13T10:29:40.440408737Z caller=factory.go:52 msg="loading bucket configuration"
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: level=info name=store ts=2023-07-13T10:29:40.441382033Z caller=caching_bucket_factory.go:76 msg="loading caching bucket configuration"
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: level=info name=store ts=2023-07-13T10:29:40.447893836Z caller=redis.go:48 msg="created redis cache"
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: level=info name=store ts=2023-07-13T10:29:40.448758864Z caller=factory.go:35 msg="loading index cache configuration"
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18d802e]
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: goroutine 1 [running]:
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: github.com/rueian/rueidis.(*clusterClient)._pick(0x0, 0x25?)
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: #011/go/pkg/mod/github.com/rueian/rueidis@v0.0.93/cluster.go:205 +0x2e
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: github.com/rueian/rueidis.(*clusterClient).single(...)
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: #011/go/pkg/mod/github.com/rueian/rueidis@v0.0.93/cluster.go:167
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: github.com/rueian/rueidis.NewClient({{0x45d964b800, {0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...}, ...})
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: #011/go/pkg/mod/github.com/rueian/rueidis@v0.0.93/rueidis.go:277 +0x25d
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: github.com/thanos-io/thanos/pkg/cacheutil.NewRedisClientWithConfig({_, _}, {_, _}, {{0xc0001ccb10, 0xf}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: #011/app/pkg/cacheutil/redis_client.go:224 +0x3f8
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: github.com/thanos-io/thanos/pkg/cacheutil.NewRedisClient({0x2b418e0, 0xc0000ca4b0}, {0x25f1c4b, 0xb}, {0xc000841e00?, 0x5f3c01?, 0xc000841a00?}, {0x2b53b
50, 0xc0000cafa0})
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: #011/app/pkg/cacheutil/redis_client.go:171 +0x191
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: github.com/thanos-io/thanos/pkg/store/cache.NewIndexCache({0x2b418e0, 0xc0000ca4b0}, {0xc0006d2000, 0x17e, 0x180}, {0x2b53b50, 0xc0000cafa0})
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: #011/app/pkg/store/cache/factory.go:58 +0x229
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: main.runStore(_, {_, _}, _, {_, _}, {_, _, _}, {0xc00045dee0, ...}, ...)
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: #011/app/cmd/thanos/store.go:313 +0x985
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: main.registerStore.func1(0x22d9340?, {0x2b418e0, 0xc0000ca4b0}, 0x6?, {0x2b53a60, 0x4057e40}, 0x4027980?, 0x0)
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: #011/app/cmd/thanos/store.go:214 +0x2a8
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: main.main()
Jul 13 15:59:40 Thanos-Store-Receiver-0 store[436391]: #011/app/cmd/thanos/main.go:133 +0x1235
Jul 13 15:59:40 Thanos-Store-Receiver-0 systemd[1]: thanos-store.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 13 15:59:40 Thanos-Store-Receiver-0 systemd[1]: thanos-store.service: Failed with result 'exit-code'.
Jul 13 15:59:40 Thanos-Store-Receiver-0 systemd[1]: thanos-store.service: Scheduled restart job, restart counter is at 1.



Local Redis is working but AWS redis cluster not working connectivity is open between store and redis, used end point and IP address also but showing same error

**Comment by grootsadmin** [comment] 2023-07-14 09:08
@GiedriusS i am not able to set the cache on redis 7.x and same not able to get cpuld you please help how to resolve this error or can you please share the thanos store redis configuration yaml file, so ill refer and verify that

**Comment by grootsadmin** [comment] 2023-07-17 12:22
@GiedriusS any update on above query

**Comment by 5cat** [comment] 2023-07-22 17:21
I can confirm that increasing the timeouts made the warning go away. 
I just dont understand why do I have to make the timeout 30s where there is client side caching enough for the whole query result. Even when I made `PoolSize`, `MaxGetMultiConcurrency`, `GetMultiBatchSize`, `MaxSetMultiConcurrency`, and `SetMultiBatchSize` equals to one since I thought doing concurrent operations might be the reason for it timing out, but still it needs that 30s timeout.

**Comment by 5cat** [comment] 2023-07-23 07:06
I'm not sure exactly what happened, but after upgrading my thanos sidecar to `v0.31.0` the caching started working correctly. 
Before that the queries did not seem to get faster after each api call and were stuck on 20s, now the 20s is just the first time, subsequent calls are taking like 2s.

**Comment by grootsadmin** [comment] 2023-07-24 05:26
@5cat Thanks for the update, could you please confirm when search historical data does it works fine or getting SET and GET error in redis
