### ISSUE TITLE
Feature request: Custom Retention policies for single metrics or groups of metrics

### ISSUE THREAD

**Issue by Breee** [thanos-io/thanos#1861] opened 2019-12-10 12:33 UTC
We thought about Retention policies for single metrics or groups of metrics.

The motiviation behind this is, that we have metrics we want to store really long or even forever, 
while other-metrics are not of interest for a long time.   

Do you think this could be useful for others too?

**Comment by bwplotka** [comment] 2019-12-10 18:41
Duplicate of https://github.com/thanos-io/thanos/issues/903

**Comment by bwplotka** [comment] 2019-12-10 18:41
Definitely useful, let's discuss on mentioned issue HOW to achieve it (:

**Closed by bwplotka** 2019-12-10 18:41 UTC
Labels: duplicate
