### ISSUE TITLE
compact: deal with thanos-receive HA blobs

### ISSUE THREAD

**Issue by sepich** [thanos-io/thanos#2116] opened 2020-02-10 13:37 UTC
**Thanos, Prometheus and Golang version used**:
v0.10.1

**Object Storage Provider**:
AWS S3

**What happened**:
We've set up 3 HA thanos-receive nodes with `--receive.replication-factor=3` and `--label=replica="$(NAME)"`.
On thanos-query side this works fine with `--query.replica-label=replica`.
But this leads to 3x space used on S3:
```
|            ULID            |        FROM         |        UNTIL        |  RANGE   | UNTIL-DOWN |  #SERIES  |   #SAMPLES    |   #CHUNKS   | COMP-LEVEL | COMP-FAILED |          LABELS          | RESOLUTION |  SOURCE   |
|----------------------------|---------------------|---------------------|----------|------------|-----------|---------------|-------------|------------|-------------|--------------------------|------------|-----------|
| 01E0DJRTRCQM3ZVQ3XWVSFKBGV | 23-01-2020 00:00:00 | 06-02-2020 00:00:00 | 336h0m0s | -296h0m0s  | 2,698,507 | 5,147,591,926 | 210,376,397 | 5          | false       | replica=thanos-receive-1 | 0s         | compactor |
| 01E0DPB9G08FQ2D33AWBTNDPC0 | 23-01-2020 00:00:00 | 06-02-2020 00:00:00 | 336h0m0s | -296h0m0s  | 2,670,996 | 5,154,572,850 | 200,780,620 | 5          | false       | replica=thanos-receive-2 | 0s         | compactor |
| 01E0DV7VAZGK657RXSTCPVNGHC | 23-01-2020 00:00:00 | 06-02-2020 00:00:00 | 336h0m0s | -296h0m0s  | 2,695,844 | 5,149,216,439 | 232,443,752 | 5          | false       | replica=thanos-receive-0 | 0s         | compactor |
```

**What you expected to happen**:
Would be great to have some option on compactor side to deduplicate blobs against some `replica-label`.

**Comment by brancz** [comment] 2020-02-10 14:53
This is a dupe of #1014 . I very much agree this is something we should have (and it's actively being worked on)! :)

**Closed by brancz** 2020-02-10 14:53 UTC
