### ISSUE TITLE
Golang runtime errors

### ISSUE THREAD

**Issue by mhoffm-aiven** [thanos-io/thanos#6862] opened 2023-10-31 08:17 UTC
**Thanos, Prometheus and Golang version used**:

Thanos built from `9c9a209ceb92b981f2dc16acd1b2441fce5183bf`. 

**Object Storage Provider**:

S3

**What happened**:

Thanos Store and Receiver frequently panic with diverse flavors of "fatal error: ". Store mostly with `fatal error: fault` and Routing receiver mostly with `fatal error: invalid g status` or `fatal error: traceback did not unwind completely`.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure yet

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by RodrigoMenezes-Vantage** [comment] 2024-06-21 18:21
Most likely the same issue as https://github.com/thanos-io/thanos/issues/6942

**Comment by MichaHoffmann** [comment] 2024-06-22 09:57
Duplicate of #6942  as mentioned by @RodrigoMenezes-Vantage

**Closed by MichaHoffmann** 2024-06-22 09:57 UTC
