### ISSUE TITLE
compactor: Internal DownsampleRange Corrupt Retention Setting

### ISSUE THREAD

**Issue by ethernoy** [thanos-io/thanos#3716] opened 2021-01-13 02:42 UTC
**Thanos, Prometheus and Golang version used**:
Thanos: 0.17.1
Prometheus: 2.22.1
Golang: not specified in our implementation :(

**Object Storage Provider**: MinIO

**What happened**:
I configured Thanos Compactor with retention period as follows:
Raw resolution: 1d
5m resolution: 14d
1h resolution: 360d

However, raw resolution data block is deleted right after it is older than 24 hrs, before it is downsampled to 5m resolution. Hence there is no 5m resolution block generated.

**What you expected to happen**:

Raw resolution data block is downsampled before it is deleted.

**How to reproduce it (as minimally and precisely as possible)**:

Set retention as above in Thanos Compactor.

**Anything else we need to know**:

I believe this is due to downsamplerange setting in [downsample.go](https://github.com/thanos-io/thanos/blob/master/pkg/compact/downsample/downsample.go). Can you calculate it dynamically or let user override this variable in parameter?

**Comment by kakkoyun** [comment] 2021-02-12 09:59
Thanks, @ethernoy for reporting. We need to investigate and validate. Help wanted and PRs are welcome.

**Comment by yeya24** [comment] 2021-03-20 23:08
This is not a bug. If you want to have raw blocks downsampled to 5m downsampled blocks, you need to set the raw retention time to >= 40h.
About dynamic or configurable downsampling interval, I think it is already discussed in https://github.com/thanos-io/thanos/issues/2408.

@ethernoy  I will close this issue. If you have further questions regarding this, feel free to reopen it.

**Closed by yeya24** 2021-03-20 23:08 UTC
Labels: beer, component: compact, help wanted, needs-investigation

**Comment by ethernoy** [comment] 2021-03-30 10:31
> This is not a bug. If you want to have raw blocks downsampled to 5m downsampled blocks, you need to set the raw retention time to >= 40h.
> About dynamic or configurable downsampling interval, I think it is already discussed in #2408.
> 
> @ethernoy I will close this issue. If you have further questions regarding this, feel free to reopen it.

I understand it completely now and thank you so much for your kind explanation! However, will you consider providing a table of the minimal length of a block of each downsampling level? For example:

| Downsample      | Minimal Length of Block |
| ----------- | ----------- |
| Raw->5m | 4h |
| 5m->1h | 7d  |
