### ISSUE TITLE
`make test-e2e` leaves behind garbage directories.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2587] opened 2020-05-11 11:57 UTC
We are leaking some `e2e` directories. Let's find why we are not cleaning them.

For now, as a workaround, we added `gitignore` entry. (https://github.com/thanos-io/thanos/pull/2552)

This only fixes the outcome, not the root cause.

**Comment by ranjithkumar007** [comment] 2020-05-11 22:10
When we call [s.Close()](https://github.com/cortexproject/cortex/blob/2e9a8b5cf531aecd84bde1607b699baaa06e9ab4/integration/e2e/scenario.go#L145) on a scenario, we [clean](https://github.com/cortexproject/cortex/blob/2e9a8b5cf531aecd84bde1607b699baaa06e9ab4/integration/e2e/scenario.go#L155) the garbage directories(ideally this should happen).
But the problem here is with the ownership of files inside these garbage directories.
![issue](https://user-images.githubusercontent.com/17480353/81608830-82900000-93f4-11ea-9053-75f3c1b29290.png)

As seen above, all the files under  `e2e_integration_test206010889/data/prometheus/ha1/` directory are with ownership `root:root` where as the directory `e2e_integration_test206010889/data/prometheus/ha1`  is `user:user`.

`ha1` is the `--tsdb.path` argument passed to  `sidecar` [service](https://github.com/thanos-io/thanos/blob/3a5038345dadf674923867c7c8c6f72a52c75280/test/e2e/e2ethanos/services.go#L102) which  is [started](https://github.com/cortexproject/cortex/blob/081f824d6998575d958715053bc84070f46d3c05/integration/e2e/service.go#L104) inside `docker`. 
I think the issue is that the user is set to `root` [here](https://github.com/thanos-io/thanos/blob/c7c7da2d51f5f7adaa2e3e37bf057beba16c21de/test/e2e/e2ethanos/services.go#L80) and [here](https://github.com/thanos-io/thanos/blob/c7c7da2d51f5f7adaa2e3e37bf057beba16c21de/test/e2e/e2ethanos/services.go#L300)([default](https://docs.docker.com/engine/reference/run/#user) user is also `root`). This is the reason why directories are created with `root:root` permission. 
May be we can set `--user $(id -u)` to fix this?

**Comment by bwplotka** [comment] 2020-05-12 11:23
Let's try this why not. This might mean a contribution to Cortex e2e framework

**Comment by ranjithkumar007** [comment] 2020-05-14 15:42
I tried this: `receiver.SetUser(strconv.Itoa(os.Getuid()))` and likewise for other services. I came across an issue with this approach while running e2e tests. relevant log line below:
```
receive-1: level=info name=receive-1 ts=2020-05-14T14:58:24.81110881Z caller=http.go:81 component=receive service=http/server component=receive 
msg="internal server shutdown" err="serve HTTP and metrics: listen tcp :80: bind: permission denied"
```

receiver tries to bind to port 80. But as ports below 1024 can be opened only by root and I set user as non-root, it causes out error.

**Comment by ranjithkumar007** [comment] 2020-05-14 16:03
do we need http service on port 80 or is it configurable?

**Comment by kakkoyun** [comment] 2020-06-15 16:22
Fixed by https://github.com/thanos-io/thanos/pull/2755

**Closed** 2020-06-17 11:19 UTC
Labels: bug, difficulty: medium, good first issue, help wanted
