### ISSUE TITLE
too manny "unsupported type of io.Reader" warnings

### ISSUE THREAD

**Issue by venkatnpedada** [thanos-io/thanos#3873] opened 2021-03-04 11:22 UTC
Thanos, Prometheus and Golang version used:

`Build Information
Version	0.17.2
Revision	37e6ef61566c7c70793ba6d128f00c4c66cb2402
Branch	HEAD
BuildUser	root@92283ccb0bc0
BuildDate	20201208-10:00:57
GoVersion	go1.15`

**Object Storage Provider**:
MiniO S3

**What happened**:
Too many warning logs 
level=warn ts=2021-03-02T09:02:42.039730584Z caller=s3.go:399 msg="could not guess file size for multipart upload; upload might be not optimized" name=debug/metas/01EZS2RSX37B27ABYDE5HMWRJS.json err="unsupported type of io.Reader"

**Comment by ahurtaud** [comment] 2021-03-04 15:22
Hello, @venkatnpedada , This issue has been fixed in version 0.18.0.

duplicate of: https://github.com/thanos-io/thanos/issues/3470

**Comment by GiedriusS** [comment] 2021-03-04 18:05
Please update to 0.18.0 or newer and see if it helps. Closing as per @ahurtaud 's message. Let us know if that didn't help and you want this to be reopened.

**Closed by GiedriusS** 2021-03-04 18:05 UTC

**Comment by venkatnpedada** [comment] 2021-03-10 10:48
@ahurtaud  @GiedriusS Not seeing this issue in 0.18.0 version. Thanks
