### ISSUE TITLE
query: error in #1904 - /series with SkipChunks not use start/end args.

### ISSUE THREAD

**Issue by IKSIN** [thanos-io/thanos#2011] opened 2020-01-20 15:09 UTC
**Thanos, Prometheus and Golang version used**:
thanos v0.10.0 with #1904 

**Object Storage Provider**:

**What happened**:
/series return all data (not considering selected time range in Grafana)

**What you expected to happen**:
Return data only in selected time range

**How to reproduce it (as minimally and precisely as possible)**:
Request /series to prometheus with start/end args and compare with same request to thanos-query

**Full logs to relevant components**:

**Anything else we need to know**:

I try to set `SkipChunks=false` and get vallid response

**Comment by GiedriusS** [comment] 2020-01-20 15:45
Thanks for the report! At first glance, it seems like the problem is here: https://github.com/thanos-io/thanos/pull/1904/files#diff-83652b446ecd7da3f50669bd4a6d44baR664-R667 - `q.Encode()` should be called after adding **all** of the parameters. For some reason, we call it before adding start/end times. @yeya24 does that sound about right?

**Comment by yeya24** [comment] 2020-01-20 17:54
Thanks for the report. I will send a fix ASAP

**Comment by yeya24** [comment] 2020-01-20 17:58
> Thanks for the report! At first glance, it seems like the problem is here: https://github.com/thanos-io/thanos/pull/1904/files#diff-83652b446ecd7da3f50669bd4a6d44baR664-R667 - `q.Encode()` should be called after adding **all** of the parameters. For some reason, we call it before adding start/end times. @yeya24 does that sound about right?

I think you are right! Thanks!

**Comment by GiedriusS** [comment] 2020-01-20 20:14
@yeya24 let me know if you need any help. It would be nice to release `0.10.1` with the one other fix that we have for alerting rules + this one :p

**Comment by bwplotka** [comment] 2020-01-23 07:37
This should be fixed, we will be releasing 0.10.1 with this.

**Closed** 2020-01-23 07:36 UTC
Labels: bug, component: query

**Comment by bwplotka** [comment] 2020-01-23 07:37
cc @GiedriusS
