### ISSUE TITLE
[Query/Sidecar] Performance issue

### ISSUE THREAD

**Issue by alexandv** [thanos-io/thanos#2323] opened 2020-03-25 14:46 UTC
**Thanos, Prometheus and Golang version used**:

Thanos 0.11 (Docker)
Prometheus 2.16 (Docker)
Go: Using the precompiled binaries from the docker images

**Object Storage Provider**:

GCS

**What happened**:

I'm using a Grafana dashboard with 14 graphs over a 5 minutes timeframe. This dashboard queries series that generate around 20K samples per second. It uses queries similar to `sum(rate(<metric>[30s]))`

The dashboard loads fast (less than half a second) when using Prometheus as the datasource but when going through Thanos it takes 5 to 10 times more.

I removed the store GW component as a query endpoint and I kept only the Prometheus sidecar as the only store API endpoint.

Parameters used for query:
```
- args:
    - query
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:9090
    - --store=prometheus:10901
```
Prometheus:
```
  - args:
    - --config.file=/etc/prometheus/prometheus.yaml
    - --storage.tsdb.path=/prometheus/
    - --storage.tsdb.retention=1d
    - --storage.tsdb.retention.size=7GB
    - --storage.tsdb.min-block-duration=2h
    - --storage.tsdb.max-block-duration=2h
```
Sidecar:
```
  - args:
    - sidecar
    - --tsdb.path=/prometheus/
    - --prometheus.url=http://127.0.0.1:9090
    - '--objstore.config={type: GCS, config: {bucket: ***}}'
```

I didn't find any specific queries in the dashboard that was causing the slowness. Removing graphs from the dashboards improves the situation but proportionally to the number of graphs removed.

Is that simply related to the fact that the raw samples need to be transferred over the network first from the sidecar to the query component? Is there any other possible explanation or ways to improve that?

**What you expected to happen**:

Same (or close to same) performance than with Prometheus

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

Grafana, Thanos Query and Prometheus/Sidecar are all running in the same Kubernetes cluster.

**Comment by bwplotka** [comment] 2020-03-28 14:46
Hi :wave: 

It's very possible that lack of chunk iterator is causing some latency for large amount of series and samples. Samples are decoded / encoded for no reason on Prometheus side, we are super soon to fix this. Once done I will ping you here so you can help us test it if you want! :hugs: 

Work in progress: https://github.com/prometheus/prometheus/pull/7059

**Comment by alexandv** [comment] 2020-03-30 22:36
Thanks @bwplotka 
Please let me know when it's ready and I'll test it.

**Comment by mrsimo** [comment] 2020-03-31 17:18
Hi there! Could this be similar to what we see in https://github.com/thanos-io/thanos/issues/2295?

**Comment by bwplotka** [comment] 2020-04-01 14:12
Potentially, will comment there.

**Comment by bwplotka** [comment] 2020-04-01 14:16
Looks indeed like @mrsimo is right this issue is duplicate of the https://github.com/thanos-io/thanos/issues/2295, so closing this one, and let's move the discussion there :hugs:

**Closed by bwplotka** 2020-04-01 14:16 UTC

**Comment by mrsimo** [comment] 2020-04-01 14:25
Thanks a lot @bwplotka!
