### ISSUE TITLE
can thanos support long-time downsample? such as --retention.resolution-1d or 1month ？

### ISSUE THREAD

**Issue by ly123-liu** [thanos-io/thanos#2498] opened 2020-04-22 10:31 UTC
HI, we want to keep longer monitor metrics for about one year or two year, can thanos suppert longger time  downsample,  1d or 1month ? thanks

**Comment by belm0** [comment] 2020-04-23 01:24
duplicate of #2408 I think

**Comment by bwplotka** [comment] 2020-04-23 12:50
Yup

**Closed by bwplotka** 2020-04-23 12:50 UTC
