### ISSUE TITLE
query: inflated rate during counter reset

### ISSUE THREAD

**Issue by llaaiiqq** [thanos-io/thanos#1326] opened 2019-07-12 17:58 UTC
Version 0.5.0 on go1.12.5

I'm sometimes seeing unexpected spikes in my rate queries during counter resets:
![rate vs count](https://user-images.githubusercontent.com/625718/61147152-8f6c5c00-a490-11e9-8d25-1d78d084e22d.jpg)

The deduplicated counter is an accurate representation of the two replicas:
![count_by_replica](https://user-images.githubusercontent.com/625718/61147382-115c8500-a491-11e9-8ef7-a5a7e29b2969.jpg)

Looking at the numbers with dedup=false there's a small overlap where one of the replicas reports the reset a few samples before the other, which might be a factor if the rate is being calculated across replicas:

ts | replica a | replica b | deduplicated | [5m] rate
-- | -- | -- | -- | --
1562945818 | 46906 | 47000 | 47000 | 2.4
1562945832 | 42 | 47000 | 47000 | 2.31
1562945846 | 66 | 47000 | 66 | 168.8
1562945860 | 66 | 115 | 66 | 164.81
1562945874 | 66 | 115 | 66 | 162.58
1562945888 | 66 | 201 | 201 | 163.5

**Comment by FUSAKLA** [comment] 2019-07-15 14:09
I have to look more closely into it but I think we are also seeing this bug from time to time jus did not find the time to analyze it.

**Comment by cwolfinger** [comment] 2019-07-22 17:59
I am also seeing a very similar issue where the following query:
```avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (hostname)*100.00```

Host-1 = 98.98200000001816
Host-2 = 1596023.3499794072
Host-3 = 95.270366926

**Comment by cwolfinger** [comment] 2019-07-22 18:30
To add a further comment - if I add the following filters:
- replica="prometheus-0"
- replica="prometheus-1"
- replica="prometheus-2"
- replica=~"prometheus-[0|1]"
The results are all ok - if I mix in the any of the following filters the results are incorrect:
- replica=~"prometheus-[1|2]" - max value seen in returned query  110
- replica=~"prometheus-[0|2]" - result value seen in returned query 500,000
So the addition of the 3rd replica seems to cause the "rate / irate" function to misbehave - there are no unusual logs in the thanos-sidecar or the thanos query or the prometheus.

Version used is .6

**Comment by cwolfinger** [comment] 2019-07-23 17:17
Further comment the spikes I am seeing are not related to counter resets.

**Comment by FUSAKLA** [comment] 2019-08-18 19:57
So I finally found the time to look into this.

I think the issue is in de-duplication in combination with `increase` or `rate` and somehow frequent holes in HA Prometheus replicas (rolling update + some SD delay, rolling update of HA Prometheus instances, target's `/metrics` endpoint randomly timing out). Unfortunately I'm not able to simulate it.

The exact symptom is way higher increase for deduplicated query than for increases for separate replicas without the deduplication 
![Screenshot-20190818213707-1896x670](https://user-images.githubusercontent.com/6112562/63229534-8db95500-c201-11e9-9c8a-b63ea5bf195d.png)

Interesting part is that raw data seems to look ok for the same range selector
![Screenshot-20190818213729-1893x772](https://user-images.githubusercontent.com/6112562/63229559-c8bb8880-c201-11e9-9ec5-db249dbfd2e3.png)

So this leads to my suspicion on the combination of deduplication and increase. 
If anyone has any clues where to look I'll be glad for any direction or advice. I'm going through the whole query evaluation code path to the PromQL engine and trying to find any possible clue so it's going slowly.

**Comment by miclando** [comment] 2019-08-19 12:56
are there plans to address this issue?

**Comment by FUSAKLA** [comment] 2019-08-20 07:55
Finally managed to create a test case where the issue happens so now I can at least verify if I manage to fix it :smile:

**Comment by FUSAKLA** [comment] 2019-08-26 10:02
Ok, so the issue is caused by counter resets as suspected. The root cause is that because of those resets and one replica managing to scrape the target one more time than the other it has higher counter value. Illustrated on the next two figures. There were timeouts on target scrapes and some target restarts during that observation time.

1. Raw data in the chunk returned by the Thanos query for the query for both replicas
![chunk_data](https://user-images.githubusercontent.com/6112562/63679022-ba1c3500-c7f0-11e9-94b0-a8f11fbd6d41.png)


2. Data returned by the iterator with counter resets applied
![iterator_data](https://user-images.githubusercontent.com/6112562/63678895-70cbe580-c7f0-11e9-93da-88674da35e9c.png)


This data chunk is returned by the Thanos query for instant query `increase(metric_name[2m])`. 
The time range used for evaluation `2m` is highlighted with the yellow stripes. The blue replica `a` has lower timestamps of data points which is preferred by the deduplication algorithm so it is the main replica. But if this replica goes down, the algorithm will switch after applying the penalty to the backup `b` replica. But this other replica has lower value which is then treated in `increase` or `rate` function evaluation as a reset and is handled that way. So the b replica value is added to the previous `a` replica value. This leads to those enormous spikes.

Few interesting findings:
- the counter reset handling is applied on two places:
   - in the [`extrapolatedRate`](https://github.com/prometheus/prometheus/blob/8fdfa8abeaaaf021d3ca614e4b50af317b1f4145/promql/functions.go#L65) function in PromQL
   - in the Thanos `CounterSeriesIterator` function [`Next`](https://github.com/thanos-io/thanos/blob/c35d47b41954dae0e9b5592cb327bf0896e78e26/pkg/compact/downsample/downsample.go#L547)
- Using the `CounterSeriesIterator` causes the query to be affected by the data out of the range selector time interval, If the deduplication took place before applying the counter resets (as on the figure 1) the result will be ok.


---

I tried to switch to the `newChunkSeriesIterator(its)` here same way as other aggregates and it resolves this one particular issue.
https://github.com/thanos-io/thanos/blob/865d5ec710b5651ead08a7dc73864a6f5dbeeaa9/pkg/query/iter.go#L143


But I'm sure the `CounterSeriesIterator` has it's reason to be there so it won't be definitely so easy :) 

Unfortunately we are hitting this issue from time to time and when it happens in SLO calculations it ruins them completely so it is pretty serious bug for us.. I'd be glad to fix it but we need to discuss how to do it. Applying deduplication before the counter resets could solve it but I'm not sure if this is the right way or should we switch to completely different solution of deduplication?

**Comment by bogdanov1609** [comment] 2019-09-25 13:17
Did you manage to discuss the solution of the problem? We faced the same issue.

**Comment by FUSAKLA** [comment] 2019-09-28 14:36
Hi, sorry for the delay. Unfortunately I did not find the time but next week I should manage to get to it.
I actually tested the deduplication before counter resets with success but I need to dig in more to see what  would be impact of such change. I'm afraid it could cause issues with down sampled data.

**Comment by bwplotka** [comment] 2020-02-27 11:48
Still, to investigate.

**Comment by bwplotka** [comment] 2020-04-20 12:21
Not fixed.

**Comment by ipstatic** [comment] 2020-04-20 14:14
@FUSAKLA did you ever find a solution to this? We are hitting this issue now.

**Comment by bwplotka** [comment] 2020-04-21 15:49
Just curious @superQ if this is not the exactly same issue as we started to investigate here: https://github.com/thanos-io/thanos/issues/2401

Let's join forces (((:

**Comment by bwplotka** [comment] 2020-04-28 14:58
Ok, I can confirm this is the same as https://github.com/thanos-io/thanos/issues/2401

Given the other issue is more active (I described all the details on findings) I will close this issue as duplicate https://github.com/thanos-io/thanos/issues/2401

**Closed by bwplotka** 2020-04-28 14:58 UTC
Labels: bug, component: query, difficulty: hard, help wanted, priority: P0
