### ISSUE TITLE
Unable to authenticate against S3 using an IAM role

### ISSUE THREAD

**Issue by edshelton** [thanos-io/thanos#1850] opened 2019-12-09 11:14 UTC
**Thanos, Prometheus and Golang version used**:
Thanos v0.8.1
Prometheus v2.13.1
EKS v1.14.7
kube2iam v0.10.8

**Object Storage Provider**:
AWS S3

**What happened**:
Unable to upload objects to the configured S3 bucket

**What you expected to happen**:
Objects are uploaded successfully

**How to reproduce it (as minimally and precisely as possible)**:
Rather than provide an access key and secret to authenticate with AWS, attempt to assume a role via kube2iam

**Full logs to relevant components**:
thanos-sidecar logs:
```
level=info ts=2019-12-07T08:00:43.483207717Z caller=shipper.go:201 msg="upload new block" id=01DVFJGWGBGHTW8MFQNA1M6JZN
level=error ts=2019-12-07T08:00:43.498676883Z caller=shipper.go:166 msg="shipping failed" block=01DVFJGWGBGHTW8MFQNA1M6JZN err="upload meta file to debug dir: upload file /prometheus/thanos/upload/01DVFJGWGBGHTW8MFQNA1M6JZN/meta.json as debug/metas/01DVFJGWGBGHTW8MFQNA1M6JZN.json: upload s3 object: Access Denied"
```

**Anything else we need to know**:

I have tested my IAM role using a debug pod in the same namespace which the Prometheus pod is running. The test pod is able assume the IAM role and put objects in the same S3 bucket which the thanos-sidecar is configured to upload to.
`kubectl run --namespace platform -i --tty --rm debug --image=mesosphere/aws-cli --restart=Never --overrides='{"metadata":{"annotations":{"iam.amazonaws.com/role": "dev-eks-thanos", "sidecar.istio.io/inject": "false"}}}' -- s3 ls s3://<redacted_bucket_name>`

This succeeds, but the thanos-sidecar in the Prometheus pod (with the same kube2iam annotation) is unable to upload objects to the same S3 bucket.

My thanos objectstore config file:

```
type: s3
config:
  bucket: <redacted_bucket_name>
  endpoint: s3.eu-west-1.amazonaws.com
  region: eu-west-1
  insecure: false
  signature_version2: false
  encryptsse: false
```
Checking for other credentials in the thanos-sidecar container directly:
```
/ $ env | grep AWS
/ $ cat ~/.aws/credentials
cat: can't open '//.aws/credentials': No such file or directory
/ $ echo $OBJSTORE_CONFIG
type: s3 config: bucket: <redacted_bucket_name> endpoint: s3.eu-west-1.amazonaws.com region: eu-west-1 insecure: false signature_version2: false encryptsse: false
```

**Comment by daixiang0** [comment] 2020-01-06 02:42
Do you mount credentials into container?

**Comment by bwplotka** [comment] 2020-01-06 10:39
I believe this is a duplicate of https://github.com/thanos-io/thanos/issues/1494

**Closed** 2020-01-06 10:39 UTC
Labels: duplicate
