### ISSUE TITLE
query-frontend 0.17.1: runtime error: index out of range

### ISSUE THREAD

**Issue by arvidsnet** [thanos-io/thanos#3515] opened 2020-11-30 06:33 UTC
I faced runtime error: `index out of range [7] with length 7` in query-frontend 0.17.1. There were huge amount of such errors (I suppose on each request), attached full log for one such error.
Unfortunately I do not know how to reproduce it, so far it happened only once.
[query-frontend-0.17.1.err.log](https://github.com/thanos-io/thanos/files/5614135/query-frontend-0.17.1.err.log)

**Comment by yeya24** [comment] 2020-11-30 15:41
Hi, thanks for the report. 
I can see this bug here https://github.com/thanos-io/thanos/blob/release-0.17/pkg/store/labelpb/label.go#L310. The `Size()` is used incorrectly. So this bug happens when the two labelsets we are comparing are exactly the same. 

But I am not sure how to reproduce this from the query frontend because before sorting, we use a set to deduplicate series so I expect there is no duplicate labelsets.

I will investigate more and check if I miss any corner case

**Comment by GiedriusS** [comment] 2020-12-07 20:51
@yeya24 this should be fixed with https://github.com/thanos-io/thanos/pull/3520, right?

**Comment by yeya24** [comment] 2020-12-07 22:52
Yes, that's correct. I will close this one.

**Closed by yeya24** 2020-12-07 22:52 UTC
Labels: bug, component: query-frontend
