### ISSUE TITLE
Frontend stuttering after upgrade to 0.10.0

### ISSUE THREAD

**Issue by bdelagesap** [thanos-io/thanos#2010] opened 2020-01-20 13:40 UTC
**Thanos, Prometheus and Golang version used**:

thanos, version 0.10.0 (branch: HEAD, revision: 698c7a922cd5dcaa53e305db5c2adb4e79d328ba)
  build user:       circleci@07a502f4439b
  build date:       20200113-14:49:31
  go version:       go1.13.1

Running current 0.10.0 docker image.
Running Prometheus 2.13.1

**Object Storage Provider**: GCS

**What happened**:
After upgrade to 0.10.0, we experience : 
-freezes and stuttering in the frontend web UI when querying using Chrome
-same behavior in Firefox until the browser actually stops responding.

Querying from Grafana (backend) is working fine.

**What you expected to happen**:
The web UI to be snappy like when we were using it with 0.8.1.

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade to 0.10.0, run query in the web UI.

**Comment by bwplotka** [comment] 2020-01-20 21:32
Thanks, can you look on the F12 (console) on chrome? What is introducing the lag in Network tab?

**Comment by bdelagesap** [comment] 2020-01-21 14:22
I do see some "stalled" time for "graph_template.handlebar" >200ms in Chrome.
In Firefox I see the "favicon" in the "stalled" state >200ms as well.

The "stalled" values are <5ms in v0.8.1.

**Comment by FUSAKLA** [comment] 2020-01-22 02:32
Hi, do you happen to have large number of metrics with distinct name?
This can cause issues with the JS when those are loaded for hinting for example.
You should see it in the browser network console as a request to `/api/v1/label/__name__/values?_=1579659568096`.

**Comment by bdelagesap** [comment] 2020-01-23 13:42
Hi
Here is what I have `api/v1/label/__name__/values?_=1579786670892`
Waiting: 672 ms, Receiving: 2.84 s
I would expect it would run this query just once.

**Comment by bwplotka** [comment] 2020-01-24 12:51
I believe it is a duplicate of https://github.com/thanos-io/thanos/issues/2011

**Closed by bwplotka** 2020-01-24 12:51 UTC
Labels: component: query, need-more-info

**Comment by bdelagesap** [comment] 2020-01-27 14:14
I installed v0.10.1 it seems we experience similar performance as with v0.8.1.
All good then, thank you.

**Comment by bwplotka** [comment] 2020-01-27 14:39
:tada:
