### ISSUE TITLE
quickstart.sh assigns wrong env variable to S3 secret key

### ISSUE THREAD

**Issue by scaleoutsean** [thanos-io/thanos#6565] opened 2023-07-27 10:54 UTC
**Thanos version used**: latest

**Object Storage Provider**: S3

**What happened**: incorrect configuration stored in data/bucket.yaml

**What you expected to happen**: correct configuration stored

**How to reproduce it (as minimally and precisely as possible)**: modify quickstart.sh and run it

The offending line is here. It should assign `MINIO_ROOT_PASSWORD`.

https://github.com/thanos-io/thanos/blob/a817dbf586244bb7cbaa182bf830ad30b7e03944/scripts/quickstart.sh#L44

I'd submit a PR but there's too much digital paperwork here.

**Comment by Vanshikav123** [comment] 2023-08-18 06:01
Hello @scaleoutsean I hope this message finds you well. I'm excited to introduce myself as a new member of the Thanos community. I'm eager to contribute to the organization and help enhance the project. If possible, could you please consider assigning me this issue , I am also open to any guidance or feedback you can provide during the process.

**Comment by matej-g** [comment] 2023-08-18 06:43
Thanks for the report @scaleoutsean! 

And thank you @Vanshikav123, please take it away! This should be straightforward 🙂.

**Comment by Vanshikav123** [comment] 2023-08-18 07:10
Thank you @matej-g for assigning me this issue . It would be great help if @scaleoutsean provide me some more information regarding this issue.

**Comment by matej-g** [comment] 2023-08-18 07:34
@Vanshikav123 I think the issue is quite straightforward - there is mistake in the parameter name, the line that was reported above needs to changed to:

```
export S3_SECRET_KEY=${MINIO_ROOT_PASSWORD} 
```

**Comment by Vanshikav123** [comment] 2023-08-18 07:39
Thank you @matej-g I have made the changes on my way to push it

**Comment by yeya24** [comment] 2023-08-18 17:24
Fixed by #6628

**Closed by yeya24** 2023-08-18 17:24 UTC
Labels: component: repo tools
