### ISSUE TITLE
query: grpc_code=Unimplemented, grpc_method=Info in 0.23.0

### ISSUE THREAD

**Issue by dmitriishaburov** [thanos-io/thanos#4717] opened 2021-09-30 14:49 UTC
**Thanos, Prometheus and Golang version used**:

Thanos: v0.23.0
Prometheus: v2.26.0

**Object Storage Provider**:

s3

**What happened**:

After updating to Thanos 0.23.0 from 0.22.0 we see constant increase in following metric:

```
grpc_client_handled_total{endpoint="http", grpc_code="Unimplemented", grpc_method="Info", grpc_service="thanos.info.Info", grpc_type="unary", 
 job="thanos-query"}
```

We have alerting for `grpc_code!="OK"` and it's triggered an alert.

**What you expected to happen**:

That counter shouldn't increment constantly

**How to reproduce it (as minimally and precisely as possible)**:

Cannot provide information right now, but probably just installing it and running queries would work.

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by GiedriusS** [comment] 2021-10-01 06:22
Hello! This seems like a duplicate of https://github.com/thanos-io/thanos/issues/4699.

**Closed by GiedriusS** 2021-10-01 06:22 UTC

**Comment by bwplotka** [comment] 2021-10-05 12:49
Fix in release and soon on master  https://github.com/thanos-io/thanos/releases/tag/v0.23.1

Thanks!
