### ISSUE TITLE
query: with grafana gives inconsistent dashboard with every refresh

### ISSUE THREAD

**Issue by maartengo** [thanos-io/thanos#5501] opened 2022-07-14 12:50 UTC
**Thanos, Prometheus and Golang version used**:
* Thanos: 11.1.0, deployed through [Bitnami helm chart](https://github.com/bitnami/charts/tree/master/bitnami/thanos), quay.io/thanos/thanos:v0.25.2
* Prometheus: 0.57.0 deployed through [kube-prometheus-stack helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)
* Grafana: v9.0.1, also through kube-prometheus-stack

**Object Storage Provider**:

**What happened**:
When using the Thanos querier as data source in Grafana, the dashboard data becomes inconsistent on every refresh. See gif for example. This doesn't happen if Grafana points directly to the Thanos sidecar. This is without usage of the storage gateway.

It might very well be a configuration issue, but we have no idea what could cause this.

![Animation](https://user-images.githubusercontent.com/46345801/178982571-2a97cb90-45f8-404c-b336-9e27097057f2.gif)

**What you expected to happen**:
Consistent data between refreshes

**How to reproduce it (as minimally and precisely as possible)**:
We haven't tried to reproduce this in a minimal setup, but it does happen on all of our environments (10+) all running the same configuration.
I can supply the complete values.yaml privately if needed, but it boils down to:

```yaml
thanos:
  storegateway:
    enabled: false
  query:
    enabled: true
    replicaLabel:
      - prometheus_replica
    dnsDiscovery:
      sidecarsService: 'prometheus-stack-kube-prom-thanos-discovery'
      sidecarsNamespace: 'prometheus'

kube-prometheus-stack:
  grafana:
    sidecar:
      datasources:
        url: http://prometheus-stack-thanos-query:9090/
        initDatasources: true
      dashboards:
        searchNamespace: ALL
        labelValue: null # Needs to be null in order to load our dashboards
  prometheus:
    replicas: 3
    thanosService:
      enabled: true
    thanosServiceMonitor:
      enabled: true
    service:
      sessionAffinity: 'ClientIP'
    prometheusSpec:
      thanos:
        objectStorageConfig:
          key: config-file.yaml
          name: thanos-secret

```

Chart:
```yaml
  - name: kube-prometheus-stack
    version: 36.6.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: thanos
    version: 10.5.5
    repository: https://charts.bitnami.com/bitnami
```

**Full logs to relevant components**:
* Grafana: no logging occurs
* Query: no logging occurs

**Anything else we need to know**:

**Environment**:
K8S on AKS. First time deploying Thanos.

**Comment by GiedriusS** [comment] 2022-07-15 06:18
It's by design due to how deduplication works - in the beginning, we need to select one "true" series. Thanos uses a heuristic - it chooses the series with the most up-to-date information. So, on each refresh, you might get a different "true" series. The typical way to solve this is to have query-frontend in front which caches past results so they won't change on each refresh. Let me know if that helps.

**Comment by roelvdberg** [comment] 2022-07-15 09:51
I have removed grafana from the test. I tried to execute a bash script with multiple queries async and the data was scrambled again after a few attempts.

`curl 'http://prometheus-stack-thanos-query-frontend:9090/api/v1/query_range' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'Referer: ' \
  -H 'content-type: application/x-www-form-urlencoded' \
  --data-raw 'query=mcps%3Akubelet_volume_stats_available%3Apercentage_mcps_workload%7BcustomerEnv%3D%22dev1%22%2CcustomerKey%3D%22ismcpsdev-dev3%22%7D&start=1657874085&end=1657877685&step=15' \
  --compressed > q1.json &

curl 'http://prometheus-stack-thanos-query-frontend:9090/api/v1/query_range' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'Referer: ' \
  -H 'content-type: application/x-www-form-urlencoded' \
  --data-raw 'query=mcps%3Acontainer_resource_memory_usage%3Apercentage%7BcustomerEnv%3D%22dev1%22%2CcustomerKey%3D%22ismcpsdev-dev3%22%7D&start=1657874085&end=1657877685&step=15' \
  --compressed > q2.json &

curl 'http://prometheus-stack-thanos-query-frontend:9090/api/v1/query_range' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'Referer: ' \
  -H 'content-type: application/x-www-form-urlencoded' \
  --data-raw 'query=mcps%3Acontainer_resource_cpu_usage%3Apercentage%7BcustomerEnv%3D%22dev1%22%2CcustomerKey%3D%22ismcpsdev-dev3%22%7D&start=1657874085&end=1657877685&step=15' \
  --compressed > q3.json &

curl 'http://prometheus-stack-thanos-query-frontend:9090/api/v1/query_range' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'Referer: ' \
  -H 'content-type: application/x-www-form-urlencoded' \
  --data-raw 'query=mcps%3Anode_memory_pressure%3Atrue%7BcustomerEnv%3D%22dev1%22%2CcustomerKey%3D%22ismcpsdev-dev3%22%7D&start=1657874085&end=1657877685&step=15' \
  --compressed > q4.json &`

**Comment by UUIDNIE** [comment] 2022-07-15 19:10
Can confirm, saw the same issue using Grafana 9.0.3 with Thanos 0.27.0 + Prometheus 2.32.1.

**Comment by GiedriusS** [comment] 2022-07-16 15:35
Is it still reproducible if you disable deduplication? 🤔

**Comment by maartengo** [comment] 2022-07-18 09:40
This still happens even without deduplication

**Comment by GiedriusS** [comment] 2022-07-20 13:17
Mhm, I see it now on my own Thanos cluster on some of the panels but it's still unclear to me what causes it or how to reproduce it consistently. Perhaps if any of you have some spare time, could you please try this with different versions between 0.24.0 & 0.27.0 to see when it starts occurring?

If it happens even with deduplication then https://github.com/thanos-io/thanos/commit/9a8c984144ddb320f60d5e0e30270ed03ad45c5c https://github.com/thanos-io/thanos/commit/d218e605c2dddab041551278bc1a5f632640f791 shouldn't cause it. :thinking: 

Maybe https://github.com/thanos-io/thanos/commit/54a0deb98237e4474d6d3d0df70ea3d08869e859 is the culprit? Could you please try to see if reverting it helps? :thinking:

**Comment by rphua** [comment] 2022-07-22 13:09
We've tested with 0.24.0, 0.25.0 and 0.26.0 they all don't seem to have the issue, only since 0.27.0.

**Comment by cuyoung** [comment] 2022-07-23 18:48
We saw the same behavior after upgrading from 0.25.2 to 0.27.0. Downgrading just the Querier to 0.26.0 resolved the issue.

In our case Grafana was receiving out of order samples and illogical results(results in billions when they should be in hundreds).

**Comment by ddreier** [comment] 2022-07-25 19:32
We had gone back down to Thanos 0.24.0, but have since moved to 0.26.0 and are **not** having any problems.

**Comment by GiedriusS** [comment] 2022-08-03 18:46
Could you please try reverting https://github.com/thanos-io/thanos/pull/5410 and see if it helps? I'll try looking into this once I'll have some time.

**Comment by dswarbrick** [comment] 2022-08-08 11:16
I also encountered this after upgrading from 0.26.0 to 0.27.0. Initially it appeared to only be present when using query frontend, but I later encountered it with just the plain querier. Also it's not specific to Grafana environments - I noticed the same weird data even when using the thanos query web UI.

**Comment by GiedriusS** [comment] 2022-08-10 11:04
Was able to reproduce this by myself. Reverting https://github.com/thanos-io/thanos/pull/5410 doesn't help, must be something more serious. Will try to reproduce locally && fix it.

**Comment by GiedriusS** [comment] 2022-08-10 19:09
Could you please try out `main-2022-08-10-d00a713a` or later and see if it helps?

**Comment by GiedriusS** [comment] 2022-08-12 06:24
Can't reproduce this anymore with https://github.com/thanos-io/thanos/commit/d00a713a9bd66e650418bde6bd80ac7f2dc67428, will close this issue in a few days if nothing comes up.

**Closed** 2022-08-17 08:30 UTC
Labels: bug, priority: P0

**Comment by hanjm** [comment] 2022-08-19 12:31
@yeya24 could you help release 0.27.1 for this important bug fix 😄

**Comment by yeya24** [comment] 2022-08-19 17:43
> @yeya24 could you help release 0.27.1 for this important bug fix 😄

cc @matej-g and @wiardvanrij

**Comment by Antiarchitect** [comment] 2022-08-23 22:50
Having the same troubles. Please issue a patch release :)

**Comment by wiardvanrij** [comment] 2022-08-30 14:20
Still catching up, but https://github.com/thanos-io/thanos/releases/tag/v0.28.0 would be the fastest fix forward to get unblocked. I'll discuss if someone can make a patch
