### ISSUE TITLE
query-frontend: fails to start when memcached dns_provider_update_interval is zero

### ISSUE THREAD

**Issue by filippog** [thanos-io/thanos#3324] opened 2020-10-15 14:26 UTC
```
$ thanos --version
thanos, version 0.16.0-rc.0 (branch: non-git, revision: non-git)
  build user:       pbuilder@i7
  build date:       20201014-13:49:07
  go version:       go1.15.2
```

**What happened**:

Trying to configure query-frontend with memcached support, however there's a failure to start unless `dns_provider_update_interval` is greater than zero:

```
Oct 15 14:11:15 pontoon-thanos-01 thanos-query-frontend[14150]: level=info ts=2020-10-15T14:11:15.784709281Z caller=intrumentation.go:48 msg="changing probe status" status=ready
Oct 15 14:11:15 pontoon-thanos-01 thanos-query-frontend[14150]: panic: non-positive interval for NewTicker
Oct 15 14:11:15 pontoon-thanos-01 thanos-query-frontend[14150]: goroutine 211 [running]:
Oct 15 14:11:15 pontoon-thanos-01 thanos-query-frontend[14150]: time.NewTicker(0x0, 0xc0004d6800)
Oct 15 14:11:15 pontoon-thanos-01 thanos-query-frontend[14150]:         /usr/lib/go-1.15/src/time/tick.go:23 +0x151
Oct 15 14:11:15 pontoon-thanos-01 thanos-query-frontend[14150]: github.com/cortexproject/cortex/pkg/chunk/cache.(*memcachedClient).updateLoop(0xc0005740d0, 0x0)
Oct 15 14:11:15 pontoon-thanos-01 thanos-query-frontend[14150]:         /tmp/thanos-build/go/pkg/mod/github.com/cortexproject/cortex@v1.3.1-0.20200923145333-8587ea61fe17/pkg/chunk/cache/memcached_client.go:203 +0x7d
Oct 15 14:11:15 pontoon-thanos-01 thanos-query-frontend[14150]: created by github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcachedClient
Oct 15 14:11:15 pontoon-thanos-01 thanos-query-frontend[14150]:         /tmp/thanos-build/go/pkg/mod/github.com/cortexproject/cortex@v1.3.1-0.20200923145333-8587ea61fe17/pkg/chunk/cache/memcached_client.go:145 +0x5eb
```

**What you expected to happen**:

query-frontend starts

**How to reproduce it (as minimally and precisely as possible)**:

```
$ cat config
type: MEMCACHED
config:
  addresses: ['localhost:11211']
$ thanos query-frontend --query-range.response-cache-config-file config
level=info ts=2020-10-15T14:22:40.405649276Z caller=main.go:138 msg="Tracing will be disabled"
level=warn ts=2020-10-15T14:22:40.40630236Z caller=query_frontend.go:110 msg="memcached cache valid time set to 0, so using a default of 24 hours expiration time"
level=info ts=2020-10-15T14:22:40.408280394Z caller=query_frontend.go:189 msg="starting query frontend"
level=info ts=2020-10-15T14:22:40.408540583Z caller=intrumentation.go:48 msg="changing probe status" status=ready
panic: non-positive interval for NewTicker

goroutine 211 [running]:
time.NewTicker(0x0, 0xc0005bcf90)
        /usr/lib/go-1.15/src/time/tick.go:23 +0x151
github.com/cortexproject/cortex/pkg/chunk/cache.(*memcachedClient).updateLoop(0xc000782270, 0x0)
        /tmp/thanos-build/go/pkg/mod/github.com/cortexproject/cortex@v1.3.1-0.20200923145333-8587ea61fe17/pkg/chunk/cache/memcached_client.go:203 +0x7d
created by github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcachedClient
        /tmp/thanos-build/go/pkg/mod/github.com/cortexproject/cortex@v1.3.1-0.20200923145333-8587ea61fe17/pkg/chunk/cache/memcached_client.go:145 +0x5eb
```

However:

```
$ cat config
type: MEMCACHED
config:
  addresses: ['localhost:11211']
  dns_provider_update_interval: 1s
$ thanos query-frontend --query-range.response-cache-config-file config
level=info ts=2020-10-15T14:25:05.302816205Z caller=main.go:138 msg="Tracing will be disabled"
level=warn ts=2020-10-15T14:25:05.305842904Z caller=query_frontend.go:110 msg="memcached cache valid time set to 0, so using a default of 24 hours expiration time"
level=info ts=2020-10-15T14:25:05.307925442Z caller=query_frontend.go:189 msg="starting query frontend"
level=info ts=2020-10-15T14:25:05.308328614Z caller=intrumentation.go:48 msg="changing probe status" status=ready
level=info ts=2020-10-15T14:25:05.308622853Z caller=intrumentation.go:60 msg="changing probe status" status=healthy
level=info ts=2020-10-15T14:25:05.308643995Z caller=http.go:58 service=http/server component=query-frontend msg="listening for requests and metrics" address=:11111
```

**Anything else we need to know**:

The example configuration on https://thanos.io/tip/components/query-frontend.md/ defaults to 0 for `dns_provider_update_interval`

**Comment by yeya24** [comment] 2020-10-17 04:27
Thanks for the report! Yes, this is definitely a bug.  A quick fix would be checking the update interval in https://github.com/thanos-io/thanos/blob/master/pkg/queryfrontend/config.go#L81.

Actually there is already such a check in https://github.com/thanos-io/thanos/blob/master/pkg/cacheutil/memcached_client.go#L118. 

This inconsistency is caused by using the Cortex's Memcached library. I still think it would be better to use our own implementation with an adapter.

**Comment by filippog** [comment] 2020-10-19 10:31
Thanks @yeya24 ! I've attempted a fix at #3338 let me know what you think!

**Comment by filippog** [comment] 2020-10-19 13:11
Issue is mitigated in `master` now! I'll leave it up to you whether to close the issue or re-scope for a more general fix @yeya24

**Comment by yeya24** [comment] 2020-10-19 13:16
Thanks for the fix. I will close this one for now.

**Closed by yeya24** 2020-10-19 13:16 UTC
Labels: bug, component: query-frontend, help wanted
