### ISSUE TITLE
Question: De-duplication is returning two metric results instead of one

### ISSUE THREAD

**Issue by venugopalthati** [thanos-io/thanos#1617] opened 2019-10-09 12:51 UTC
We have two Prometheus instances scraping metrics from same services and Thanos sidecar is running in the same pod where Prometheus is running and pushing metrics to S3 storage. Thanos querier is configured to read metrics from sidecars and storage gateway and replica label as "prometheus_replica". 

We got a multiple series error in Grafana when we queried metrics from thanos querier  for last 30 days metrics. We were expecting only metric result in the output for our query but when we look at the raw data, we have two metric results. We are trying to understanding if controller_revision_hash is causing the issue or something else ? controller_revision_hash is the only value which is different in the output after de-duplication.

Metrics data before replication (removed values for readability).

```{
	"status": "success",
	"data": {
		"resultType": "matrix",
		"result": [
			{
				"metric": {
					"__name__": "cassandra_clientrequest_latency_mean",
					"app": "myapp",
					"controller_revision_hash": "myapp-5595778584",
					"instance": "myapp-0",
					"job": "kubernetes-pods",
					"kubernetes_namespace": "myapp",
					"kubernetes_pod_name": "myapp-0",
					"prometheus": "monitoring/prom-prometheus-operator-prometheus",
					"prometheus_replica": "prometheus-prom-prometheus-operator-prometheus-0",
					"run": "1",
					"statefulset_kubernetes_io_pod_name": "myapp-0",
					"type": "Read"
				},
				"values": [
				]
			},
			{
				"metric": {
					"__name__": "cassandra_clientrequest_latency_mean",
					"app": "myapp",
					"controller_revision_hash": "myapp-5595778584",
					"instance": "myapp-0",
					"job": "kubernetes-pods",
					"kubernetes_namespace": "myapp",
					"kubernetes_pod_name": "myapp-0",
					"prometheus": "monitoring/prom-prometheus-operator-prometheus",
					"prometheus_replica": "prometheus-prom-prometheus-operator-prometheus-1",
					"run": "1",
					"statefulset_kubernetes_io_pod_name": "myapp-0",
					"type": "Read"
				},
				"values": [
				]
			},
			{
				"metric": {
					"__name__": "cassandra_clientrequest_latency_mean",
					"app": "myapp",
					"controller_revision_hash": "myapp-58f9997c55",
					"instance": "myapp-0",
					"job": "kubernetes-pods",
					"kubernetes_namespace": "myapp",
					"kubernetes_pod_name": "myapp-0",
					"prometheus": "monitoring/prom-prometheus-operator-prometheus",
					"prometheus_replica": "prometheus-prom-prometheus-operator-prometheus-0",
					"run": "1",
					"statefulset_kubernetes_io_pod_name": "myapp-0",
					"type": "Read"
				},
				"values": [
				]
			},
			{
				"metric": {
					"__name__": "cassandra_clientrequest_latency_mean",
					"app": "myapp",
					"controller_revision_hash": "myapp-58f9997c55",
					"instance": "myapp-0",
					"job": "kubernetes-pods",
					"kubernetes_namespace": "myapp",
					"kubernetes_pod_name": "myapp-0",
					"prometheus": "monitoring/prom-prometheus-operator-prometheus",
					"prometheus_replica": "prometheus-prom-prometheus-operator-prometheus-1",
					"run": "1",
					"statefulset_kubernetes_io_pod_name": "myapp-0",
					"type": "Read"
				},
				"values": [
				]
			}
		]
	}
}
```

Metrics data after de-duplication  (removed values for readability).

```{
	"status": "success",
	"data": {
		"resultType": "matrix",
		"result": [
			{
				"metric": {
					"__name__": "cassandra_clientrequest_latency_mean",
					"app": "myapp",
					"controller_revision_hash": "myapp-5595778584",
					"instance": "myapp-0",
					"job": "kubernetes-pods",
					"kubernetes_namespace": "myapp",
					"kubernetes_pod_name": "myapp-0",
					"prometheus": "monitoring/prom-prometheus-operator-prometheus",
					"replica": "A",
					"run": "1",
					"statefulset_kubernetes_io_pod_name": "myapp-0",
					"type": "Read"
				},
				"values": [
				]
			},
			{
				"metric": {
					"__name__": "cassandra_clientrequest_latency_mean",
					"app": "myapp",
					"controller_revision_hash": "myapp-58f9997c55",
					"instance": "myapp-0",
					"job": "kubernetes-pods",
					"kubernetes_namespace": "myapp",
					"kubernetes_pod_name": "myapp-0",
					"prometheus": "monitoring/prom-prometheus-operator-prometheus",
					"replica": "A",
					"run": "1",
					"statefulset_kubernetes_io_pod_name": "myapp-0",
					"type": "Read"
				},
				"values": [
				]
			}
		]
	}
}
```

**Comment by jojohappy** [comment] 2019-10-10 13:42
@venugopalthati Hi, the result after deduplication seems to be correct, in prometheus, if two samples have the same labels, they will be in one series. So in your result of series, those have different value in label `controller_revision_hash`, they could not be deduplicated.

**Comment by bwplotka** [comment] 2019-10-10 15:48
@jojohappy is correct :+1: 

Closing as it's working as intended.

**Closed by bwplotka** 2019-10-10 15:48 UTC

**Comment by venugopalthati** [comment] 2019-10-10 20:41
Thanks @jojohappy @bwplotka
