### ISSUE TITLE
Liveness and readiness probes are failing with 503 in compactor and prometheus after upgrading to 0.17.0

### ISSUE THREAD

**Issue by dimm0** [thanos-io/thanos#3466] opened 2020-11-18 23:11 UTC
**Thanos, Prometheus and Golang version used**:

Thanos 0.17.0, prometheus 2.22.2

**Object Storage Provider**:
ceph S3

**What happened**:
After upgrading thanos to 0.17.0, the liveness probes in prometheus and thanos-compactor pods start failing with 503 error, which causes pods to restart

**What you expected to happen**:
Pods keep running

**How to reproduce it (as minimally and precisely as possible)**:
Not sure what triggered it, I simply upgraded a working installation

**Full logs to relevant components**:
Couldn't get any error in logs since container simply restarts, no errors logged

**Comment by dimm0** [comment] 2020-11-18 23:11
The problem is gone when reverted to 0.16.0

**Comment by kesor** [comment] 2020-11-24 11:10
When running `thanos compact --http-address=0.0.0.0:10902` it doesn't listen, checked with `netstat -na | grep LISTEN` by `exec` into the container running compact.

**Comment by Kampe** [comment] 2020-11-30 22:11
I see the same issues with using thanos store in v0.16, did not see in v0.15

**Comment by ahurtaud** [comment] 2020-12-02 18:48
We have the same issue I think.
What is weird is:
For some buckets it is working fine, for some other, it gets killed by the liveness probe.

bucket config: Scality S3

Fails on 0.17.1 and works on 0.16.0

**Comment by ahurtaud** [comment] 2020-12-02 18:52
dupe of https://github.com/thanos-io/thanos/issues/3395 ?

**Comment by bwplotka** [comment] 2020-12-02 19:02
Yup, that looks like the same issue.

Thank you all for reporting this, let's fix and release 0.17.2 (:

Also commented on the mentioned issue. Closing this one as dup :hugs:

**Closed by bwplotka** 2020-12-02 19:02 UTC

**Comment by Kampe** [comment] 2020-12-03 17:28
@bwplotka I am seeing the same behavior with this issue in thanos-store with an upgrade to 0.17 as well, while not the same component - pods will be end up redeploying after liveness checks fail for no apparent reason.
