### ISSUE TITLE
how to delete wrong data in thanos

### ISSUE THREAD

**Issue by shshxy98** [thanos-io/thanos#2215] opened 2020-03-04 06:00 UTC
we have some wrong data in thanos
we know the metric and the time rane(like 5days ago to  1days ago),
how can we delete the wrong data in this time range ?
thanks

**Comment by GiedriusS** [comment] 2020-03-04 09:57
Duplicate of https://github.com/thanos-io/thanos/issues/1598. Closing this one.

**Closed by GiedriusS** 2020-03-04 09:57 UTC
