### ISSUE TITLE
thanos (0.15 & 0.17) sidecar consume much more memory

### ISSUE THREAD

**Issue by motyla** [thanos-io/thanos#3314] opened 2020-10-14 11:31 UTC
Thanos sidecar takes a lot of memory . We used `0.13.0` which took less then 1G ram . now in version `0.15.0` we peak to more then 10-15GB

Our sidecar does not upload data to object store

**Thanos, Prometheus and Golang version used**:

thanos, version 0.15.0 (branch: HEAD, revision: fbd14b49f95e7543883fedf9381a21127d4dda2b)
  build user:       root@d35b081d3e19
  build date:       20200907-09:29:21
  go version:       go1.14.2

prometheus, version 2.21.0 (branch: HEAD, revision: e83ef207b6c2398919b69cd87d2693cfc2fb4127)
  build user:       root@a4d9bea8479e
  build date:       20200911-11:35:02
  go version:       go1.15.2

**What happened**:

After upgrade thanos to 0.15 sidecar start consuming much more memory then before

**What you expected to happen**:

Memory consumption should have stay the same 

**How to reproduce it (as minimally and precisely as possible)**:

upgrade thanos to 0.15

**Full logs to relevant components**:

sidecar running options:
```
/usr/sbin/thanos sidecar \
  --grpc-address=0.0.0.0:10801 \
  --http-address=0.0.0.0:10802 \
  --prometheus.url=http://localhost:9090 \
  --tsdb.path=/opt/prometheus-data \
  --log.level=info
```

Below memory consumption just before my systemd limit killed it
```
[  +0.000003] Task in /system.slice/thanos-sidecar.service killed as a result of limit of /system.slice/thanos-sidecar.service
[  +0.000004] memory: usage 7340032kB, limit 7340032kB, failcnt 1880
[  +0.000002] memory+swap: usage 7340032kB, limit 9007199254740988kB, failcnt 0
[  +0.000002] kmem: usage 0kB, limit 9007199254740988kB, failcnt 0
[  +0.000001] Memory cgroup stats for /system.slice/thanos-sidecar.service: cache:0KB rss:7340032KB rss_huge:0KB mapped_file:0KB swap:0KB inactive_anon:0KB active_anon:7340008KB inactive_file:0KB active_file:0KB unevictable:
[  +0.000021] [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
[  +0.000114] [75952]     0 75952  2795646  1838789    4368        0             0 thanos
[  +0.000008] Memory cgroup out of memory: Kill process 76522 (thanos) score 974 or sacrifice child
[  +0.002278] Killed process 75952 (thanos), UID 0, total-vm:11182584kB, anon-rss:7339152kB, file-rss:16004kB, shmem-rss:0kB
```

and also top heap usage
```
go tool pprof -top http://localhost:10802/debug/pprof/heap
Fetching profile over HTTP from http://localhost:10802/debug/pprof/heap
Saved profile in /root/pprof/pprof.thanos.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz
File: thanos
Type: inuse_space
Time: Oct 14, 2020 at 11:16am (UTC)
Showing nodes accounting for 6733.73kB, 100% of 6733.73kB total
      flat  flat%   sum%        cum   cum%
 1056.33kB 15.69% 15.69%  1056.33kB 15.69%  github.com/thanos-io/thanos/pkg/store.NewPrometheusStore.func1
  536.37kB  7.97% 23.65%   536.37kB  7.97%  regexp/syntax.(*compiler).inst (inline)
  521.37kB  7.74% 31.40%   521.37kB  7.74%  google.golang.org/protobuf/internal/filedesc.(*File).initDecls (inline)
  516.01kB  7.66% 39.06%   516.01kB  7.66%  github.com/aws/aws-sdk-go/aws/endpoints.init
  514.63kB  7.64% 46.70%   514.63kB  7.64%  math/rand.NewSource (inline)
     514kB  7.63% 54.33%      514kB  7.63%  bufio.NewWriterSize (inline)
     514kB  7.63% 61.97%      514kB  7.63%  github.com/prometheus/client_golang/prometheus.newSummary
  512.44kB  7.61% 69.58%   512.44kB  7.61%  runtime.allocm
  512.28kB  7.61% 77.19%   512.28kB  7.61%  reflect.mapassign
  512.19kB  7.61% 84.79%   512.19kB  7.61%  runtime.malg
  512.06kB  7.60% 92.40%   512.06kB  7.60%  net/url.parse
  512.05kB  7.60%   100%   512.05kB  7.60%  net/http.(*persistConn).roundTrip
         0     0%   100%  1024.34kB 15.21%  encoding/json.(*decodeState).object
         0     0%   100%  1024.34kB 15.21%  encoding/json.(*decodeState).unmarshal
         0     0%   100%  1024.34kB 15.21%  encoding/json.(*decodeState).value
         0     0%   100%  1024.34kB 15.21%  encoding/json.Unmarshal
         0     0%   100%   536.37kB  7.97%  github.com/asaskevich/govalidator.init
         0     0%   100%   512.06kB  7.60%  github.com/go-openapi/jsonreference.(*Ref).parse
         0     0%   100%   512.06kB  7.60%  github.com/go-openapi/jsonreference.New (inline)
         0     0%   100%   512.06kB  7.60%  github.com/go-openapi/spec.(*Ref).fromMap
         0     0%   100%  1024.34kB 15.21%  github.com/go-openapi/spec.(*Schema).UnmarshalJSON
         0     0%   100%  1024.34kB 15.21%  github.com/go-openapi/spec.MustLoadSwagger20Schema (inline)
         0     0%   100%  1024.34kB 15.21%  github.com/go-openapi/spec.Swagger20Schema
         0     0%   100%  1024.34kB 15.21%  github.com/go-openapi/spec.init.0
         0     0%   100%  1024.34kB 15.21%  github.com/go-openapi/spec.initResolutionCache
         0     0%   100%   521.37kB  7.74%  github.com/golang/protobuf/proto.RegisterType
         0     0%   100%  1568.38kB 23.29%  github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1
         0     0%   100%  1568.38kB 23.29%  github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1
         0     0%   100%  1568.38kB 23.29%  github.com/grpc-ecosystem/go-grpc-middleware/recovery.StreamServerInterceptor.func1
         0     0%   100%  1568.38kB 23.29%  github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.StreamServerInterceptor.func1
         0     0%   100%  1568.38kB 23.29%  github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1
         0     0%   100%   514.63kB  7.64%  github.com/lightstep/lightstep-tracer-go.init
         0     0%   100%   514.63kB  7.64%  github.com/lightstep/lightstep-tracer-go/lightstep/rand.(*Pool).seed
         0     0%   100%   514.63kB  7.64%  github.com/lightstep/lightstep-tracer-go/lightstep/rand.NewLockedRand
         0     0%   100%   514.63kB  7.64%  github.com/lightstep/lightstep-tracer-go/lightstep/rand.NewPool
         0     0%   100%      514kB  7.63%  github.com/prometheus/client_golang/prometheus.NewSummary
         0     0%   100%      514kB  7.63%  github.com/prometheus/prometheus/discovery/file.init
         0     0%   100%  1568.38kB 23.29%  github.com/thanos-io/thanos/pkg/store.(*PrometheusStore).Series
         0     0%   100%  1056.33kB 15.69%  github.com/thanos-io/thanos/pkg/store.(*PrometheusStore).getBuffer (inline)
         0     0%   100%  1056.33kB 15.69%  github.com/thanos-io/thanos/pkg/store.(*PrometheusStore).handleStreamedPrometheusResponse
         0     0%   100%   512.05kB  7.60%  github.com/thanos-io/thanos/pkg/store.(*PrometheusStore).startPromRemoteRead
         0     0%   100%   512.05kB  7.60%  github.com/thanos-io/thanos/pkg/store.(*PrometheusStore).startPromRemoteRead.func1
         0     0%   100%  1568.38kB 23.29%  github.com/thanos-io/thanos/pkg/store/storepb._Store_Series_Handler
         0     0%   100%   512.05kB  7.60%  github.com/thanos-io/thanos/pkg/tracing.(*tripperware).RoundTrip
         0     0%   100%   512.05kB  7.60%  github.com/thanos-io/thanos/pkg/tracing.DoInSpan
         0     0%   100%  1568.38kB 23.29%  github.com/thanos-io/thanos/pkg/tracing.StreamServerInterceptor.func1
         0     0%   100%   521.37kB  7.74%  go.etcd.io/etcd/etcdserver/etcdserverpb.init.4
         0     0%   100%  1568.38kB 23.29%  google.golang.org/grpc.(*Server).handleStream
         0     0%   100%  1568.38kB 23.29%  google.golang.org/grpc.(*Server).processStreamingRPC
         0     0%   100%  1568.38kB 23.29%  google.golang.org/grpc.(*Server).serveStreams.func1.1
         0     0%   100%   521.37kB  7.74%  google.golang.org/protobuf/internal/filedesc.Builder.Build
         0     0%   100%   521.37kB  7.74%  google.golang.org/protobuf/internal/filedesc.newRawFile
         0     0%   100%   521.37kB  7.74%  google.golang.org/protobuf/internal/impl.Export.LegacyMessageTypeOf
         0     0%   100%   521.37kB  7.74%  google.golang.org/protobuf/internal/impl.legacyLoadFileDesc
         0     0%   100%   521.37kB  7.74%  google.golang.org/protobuf/internal/impl.legacyLoadMessageDesc
         0     0%   100%   521.37kB  7.74%  google.golang.org/protobuf/internal/impl.legacyLoadMessageInfo
         0     0%   100%   512.05kB  7.60%  net/http.(*Client).Do
         0     0%   100%   512.05kB  7.60%  net/http.(*Client).do
         0     0%   100%   512.05kB  7.60%  net/http.(*Client).send
         0     0%   100%   512.05kB  7.60%  net/http.(*Transport).RoundTrip
         0     0%   100%      514kB  7.63%  net/http.(*Transport).dialConn
         0     0%   100%      514kB  7.63%  net/http.(*Transport).dialConnFor
         0     0%   100%   512.05kB  7.60%  net/http.(*Transport).roundTrip
         0     0%   100%   512.05kB  7.60%  net/http.send
         0     0%   100%   512.06kB  7.60%  net/url.Parse
         0     0%   100%   512.28kB  7.61%  reflect.Value.SetMapIndex
         0     0%   100%   536.37kB  7.97%  regexp.Compile (inline)
         0     0%   100%   536.37kB  7.97%  regexp.MustCompile
         0     0%   100%   536.37kB  7.97%  regexp.compile
         0     0%   100%   536.37kB  7.97%  regexp/syntax.(*compiler).compile
         0     0%   100%   536.37kB  7.97%  regexp/syntax.(*compiler).rune
         0     0%   100%   536.37kB  7.97%  regexp/syntax.Compile
         0     0%   100%  3114.66kB 46.25%  runtime.doInit
         0     0%   100%  3114.66kB 46.25%  runtime.main
         0     0%   100%  1024.62kB 15.22%  runtime.mstart
         0     0%   100%   512.44kB  7.61%  runtime.mstart1
         0     0%   100%   512.44kB  7.61%  runtime.newm
         0     0%   100%   512.19kB  7.61%  runtime.newproc.func1
         0     0%   100%   512.19kB  7.61%  runtime.newproc1
         0     0%   100%   512.44kB  7.61%  runtime.resetspinning
         0     0%   100%   512.44kB  7.61%  runtime.schedule
         0     0%   100%   512.44kB  7.61%  runtime.startm
         0     0%   100%   512.19kB  7.61%  runtime.systemstack
         0     0%   100%   512.44kB  7.61%  runtime.wakep (inline)
         0     0%   100%  1056.33kB 15.69%  sync.(*Pool).Get
```

**Anything else we need to know**:

prometheus was upgraded to `2.21.0` a week before thanos upgrade.

**Comment by bwplotka** [comment] 2020-10-14 20:59
Thanks for this report, this is unexpected. Can you upgrade to `v0.16.0-rc.0` so we have fresh view? pprof data with allocs would be amazing :heart:

**Comment by bwplotka** [comment] 2020-10-14 21:01
You can share ` /root/pprof/pprof.thanos.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz` as well - would be helpful anyway (:

**Comment by motyla** [comment] 2020-10-15 07:09
Here is the file. 
[pprof.thanos.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz](https://github.com/thanos-io/thanos/files/5383011/pprof.thanos.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz)

**Comment by motyla** [comment] 2020-10-19 09:42
@bwplotka  adding pprof file of same server with `v0.16.0-rc.0` just before my 10G limit kills it

[pprof_file.gz](https://github.com/thanos-io/thanos/files/5400790/pprof_file.gz)

**Comment by MMeent** [comment] 2020-10-27 11:47
I'm seeing the same happen (relatively fresh kubernetes deployment (30-ish days), Thanos v0.15.0 + prometheus v2.21.0)

It looks like every two hours (the `--storage.tsdb.min/max-block-duration`) a block is malloc-ed, but not cleaned up.

I must also note that around the first time the memory grew, the first block of size > 150MB was completed in prometheus.

Attached is a zip containing the output of `du -hd1 /data/ | sort -t / -k 3` (size of folders in the prometheus data dir, ordered by block), plus a json file containing all metadata json available at the moment. 

I have 15 days of retention in prometheus, and the first occurance of the issue was on the 17th, which is 9 days ago, so I can debug some stuff.

I also get bi-hourly logs:

> ```
> level=warn ts=2020-10-27T10:18:54.022650725Z caller=sidecar.go:311 msg="failed to get Prometheus flags. Is Prometheus running? Retrying" err="got non-200 response code: 503, response: Service Unavailable"
> ```

But this seems to be unrelated; the logs didn't start to appear until recently, whilst the memory usage of thanos has grown for a longer time.
[debug-data.zip](https://github.com/thanos-io/thanos/files/5444978/debug-data.zip)

**Comment by MMeent** [comment] 2020-10-28 11:25
Update: After setting the memory limit of the sidecar to 512MiB in k8s, the sidecar did still use more memory than expected, but by far not as much as what was previously used: 

![image](https://user-images.githubusercontent.com/2960313/97428647-9386ec00-1916-11eb-9574-4519823a9916.png)

Memory limits were imposed starting from 16:30 local time, that is the start of the red line.

One reason for the higher memory usage that I can think of, is that with the upgrade to v0.15.0, minio was upgraded from v6.x to v7.x. This version bumps' changes also includes less [aggressive memory cleanup of the buffers used in multipart uploads](https://github.com/minio/minio-go/compare/v6.0.56...v7.0.2#diff-8ad83b53e5a79960b6b121adbe9753c0e312d098f11b5dd7d9743bc8d9445d91L101), meaning that the Go runtime is not asked to clean up the buffers used in multipart uploads. And without a clear limit (cgroup?) on how much memory is available, the Go runtime will not clean up its memory when it can still allocate from the OS, as OS allocation is cheaper than a GC and cleanup.

**Comment by GiedriusS** [comment] 2020-10-31 21:35
> Update: After setting the memory limit of the sidecar to 512MiB in k8s, the sidecar did still use more memory than expected, but by far not as much as what was previously used:
> 
> ![image](https://user-images.githubusercontent.com/2960313/97428647-9386ec00-1916-11eb-9574-4519823a9916.png)
> 
> Memory limits were imposed starting from 16:30 local time, that is the start of the red line.
> 
> One reason for the higher memory usage that I can think of, is that with the upgrade to v0.15.0, minio was upgraded from v6.x to v7.x. This version bumps' changes also includes less [aggressive memory cleanup of the buffers used in multipart uploads](https://github.com/minio/minio-go/compare/v6.0.56...v7.0.2#diff-8ad83b53e5a79960b6b121adbe9753c0e312d098f11b5dd7d9743bc8d9445d91L101), meaning that the Go runtime is not asked to clean up the buffers used in multipart uploads. And without a clear limit (cgroup?) on how much memory is available, the Go runtime will not clean up its memory when it can still allocate from the OS, as OS allocation is cheaper than a GC and cleanup.

Are you talking about https://github.com/minio/minio-go/commit/51222d26253e90224f8b4f8ba9be9b7982e3ce53 ?

**Comment by MMeent** [comment] 2020-10-31 22:29
That's what I was talking about, yes

**Comment by MMeent** [comment] 2020-12-31 01:14
Did someone misconfigure their bot? This is not a PR on which we can push commits, so I don't know about the above notice.

**Comment by motyla** [comment] 2020-12-31 09:58
Still, sidecar is consuming lot's of memory. For now systemd limit (10G !!!) restart it all the time .
This happen with thanos 0.17.2 and prometheus 2.23.0

**Comment by bwplotka** [comment] 2020-12-31 10:43
No, the bot is there for a reason. The issue is stale if there no updates either from us or from a reporter. It actually did its job as it triggered you to ping us on this issue 🤗 

Hmm, this is experience is definitely not expected. Especially sidecar should be now almost transparent in resource consumption. It's streaming all the messages. The only ways we know it could grow in allocations are:

1. The remote read frame size was increased
2. There are thousands of concurrent requests

But to me, the data provided shows... almost no allocations on sidecar. 🤔 

All profiles, both https://github.com/thanos-io/thanos/issues/3314#issuecomment-708948926 and https://github.com/thanos-io/thanos/issues/3314#issuecomment-711941355 are low mem:

```
   File: thanos
Type: inuse_space
Time: Oct 19, 2020 at 10:29am (BST)
Showing nodes accounting for 7845.29kB, 100% of 7845.29kB total
```

3. are we sure it's sidecar OOM-ing not e.g Prometheus?

Especially @MMeent https://github.com/thanos-io/thanos/issues/3314#issuecomment-717870898 those graph might expected for grow until your system limit, see https://www.bwplotka.dev/2019/golang-memory-monitoring/ NOTE: This wil change soon in another Thanos version due to new Go version changes.

Anyway, let's try to dig more. If it's not 1, 2, or 3 happening, this might mean leak or unexpected allocation on the request path or the upload path. So.. let's try to answer below questions:

4. Is it a memory leak? 

In this case, allocated memory should grow in small amounts but stable until OOM. Is that a case? Or is it rather super low and suddenly huge spike?

5. Is this coming from a request path or upload path?

This more tricky. Ideally we have memory profile in the moment of high consumption period. It's easier when it's a leak but not so easy when is spike without more advanced tools like core dumps or https://github.com/conprof/conprof .. but maybe it's doable? Profile provided above is not useful - it shows only 6MB of mem allocated.

Another naive way of checking would be to start ... .2 sidecars. Configure one for upload, second for requests (point Querier to that one only). This will tell us no 2. (: 

WDYT? Can we have more input? I don't think we can reproduce this on our side.

**Comment by MMeent** [comment] 2020-12-31 11:33
> 3. are we sure it's sidecar OOM-ing not e.g Prometheus?

yes, my graphs were of only the sidecar. It didn't OOM though, the restarts are for different reasons (storage migration, configuration changes)

> Especially @MMeent #3314 (comment) those graph might expected for grow until your system limit, see https://www.bwplotka.dev/2019/golang-memory-monitoring/

Thank you for pointing me to that article. `working set` vs. `usage` is quite possibly the real culprit here: Go's profiles do not include non-working set memory.

I'll try running with `GODEBUG=madvdontneed=1` to check if that would solve this problem.

**Comment by bwplotka** [comment] 2020-12-31 11:54
> I'll try running with GODEBUG=madvdontneed=1 to check if that would solve this problem.

But that's the problem. It's not a **problem** (: It works just fine with this. It will consume as much as needed, but kernel will take it as soon as it needs it. So if something OOMs it's not because of sidecar using too much.

I wonder if this misunderstanding is also what  @motyla is seeing. 🤗 If yes, we can close this issue.

**Comment by motyla** [comment] 2020-12-31 14:01
Thanos sidecar seems to be the one to consume memory and it is the process that invoke the OOM:
```[  +0.006437] thanos invoked oom-killer: gfp_mask=0x201da, order=0, oom_score_adj=0```
Looking on thanos graph I see heap is getting huge at the place where OOM accure
![Screen Shot 2020-12-31 at 14 58 11](https://user-images.githubusercontent.com/110208/103413239-627aa000-4b81-11eb-93dc-0eccec82781c.png)

**Comment by bwplotka** [comment] 2020-12-31 16:11
>  testing now GODEBUG=madvdontneed=1

No need to, the heap is not lying (:  

Cool, can you test 0.17.2 sidecar then? It looks like request / upload short spike not a leak. Profiles would let us know. It would be also amazing to rule out sidecar using wrong remote read protocol version (should use XOR_STREAMED)

**Comment by motyla** [comment] 2021-01-03 15:09
In my case it's requests only , no cloud upload. I'm already running 0.17.2 . Attaching 2 consecutive pprof files of high memory consumption:
[heap.pprof.1.gz](https://github.com/thanos-io/thanos/files/5761770/heap.pprof.1.gz)
[heap.pprof.2.gz](https://github.com/thanos-io/thanos/files/5761771/heap.pprof.2.gz)

**Comment by motyla** [comment] 2021-01-13 13:58
I'm happy to say that issue was found and solved on my end, and indeed it was in the query path.
`/api/v1/label/__name__/values` got to huge size on our prometheus servers (bad graphite-exporter mapping config).

Once reduced, memory pressure is gone. 

10x for the help and attention    :-)

**Closed** 2021-02-06 11:25 UTC
Labels: bug, component: sidecar
